// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxArchiveStatus string

const (
	OutboxArchiveStatusSuccess OutboxArchiveStatus = "success"
	OutboxArchiveStatusFailed  OutboxArchiveStatus = "failed"
)

func (e *OutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxArchiveStatus(s)
	case string:
		*e = OutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullOutboxArchiveStatus struct {
	OutboxArchiveStatus OutboxArchiveStatus `json:"outbox_archive_status"`
	Valid               bool                `json:"valid"` // Valid is true if OutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxArchiveStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type PartiesStatus string

const (
	PartiesStatusInactive PartiesStatus = "inactive"
	PartiesStatusActive   PartiesStatus = "active"
)

func (e *PartiesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartiesStatus(s)
	case string:
		*e = PartiesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PartiesStatus: %T", src)
	}
	return nil
}

type NullPartiesStatus struct {
	PartiesStatus PartiesStatus `json:"parties_status"`
	Valid         bool          `json:"valid"` // Valid is true if PartiesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartiesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PartiesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartiesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartiesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartiesStatus), nil
}

type PartyMembersRole string

const (
	PartyMembersRoleOwner  PartyMembersRole = "owner"
	PartyMembersRoleAdmin  PartyMembersRole = "admin"
	PartyMembersRoleMember PartyMembersRole = "member"
)

func (e *PartyMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartyMembersRole(s)
	case string:
		*e = PartyMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PartyMembersRole: %T", src)
	}
	return nil
}

type NullPartyMembersRole struct {
	PartyMembersRole PartyMembersRole `json:"party_members_role"`
	Valid            bool             `json:"valid"` // Valid is true if PartyMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartyMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.PartyMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartyMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartyMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartyMembersRole), nil
}

type UsersStatus string

const (
	UsersStatusInactive UsersStatus = "inactive"
	UsersStatusActive   UsersStatus = "active"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type IdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxArchive struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID         `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID         `db:"trace_id" json:"trace_id"`
	Event          string              `db:"event" json:"event"`
	Payload        []byte              `db:"payload" json:"payload"`
	Status         OutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32               `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz  `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz  `db:"archived_at" json:"archived_at"`
}

type OutboxEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TraceID    pgtype.UUID        `db:"trace_id" json:"trace_id"`
	Event      string             `db:"event" json:"event"`
	Payload    []byte             `db:"payload" json:"payload"`
	Status     OutboxEventStatus  `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Party struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    PartiesStatus      `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PartyMember struct {
	PartyID   pgtype.UUID        `db:"party_id" json:"party_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      PartyMembersRole   `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type User struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	Email           string             `db:"email" json:"email"`
	Activated       bool               `db:"activated" json:"activated"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	IdpSubjectID    string             `db:"idp_subject_id" json:"idp_subject_id"`
	IdpProviderName string             `db:"idp_provider_name" json:"idp_provider_name"`
	Status          UsersStatus        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
