// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (
  id, name, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, status, created_at, updated_at
`

type CreatePartyParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    PartiesStatus      `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyByID = `-- name: GetPartyByID :one
SELECT id, name, status, created_at, updated_at FROM parties
WHERE id = $1
`

func (q *Queries) GetPartyByID(ctx context.Context, id pgtype.UUID) (Party, error) {
	row := q.db.QueryRow(ctx, getPartyByID, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParty = `-- name: UpdateParty :one
UPDATE parties SET
  name = $2,
  status = $3,
  updated_at = $4
WHERE id = $1
RETURNING id, name, status, created_at, updated_at
`

type UpdatePartyParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    PartiesStatus      `db:"status" json:"status"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, updateParty,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
