// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, status, created_at, updated_at, deleted_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	Email           string             `db:"email" json:"email"`
	Activated       bool               `db:"activated" json:"activated"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	IdpSubjectID    string             `db:"idp_subject_id" json:"idp_subject_id"`
	IdpProviderName string             `db:"idp_provider_name" json:"idp_provider_name"`
	Status          UsersStatus        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Activated,
		arg.AvatarUrl,
		arg.IdpSubjectID,
		arg.IdpProviderName,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Activated,
		&i.AvatarUrl,
		&i.IdpSubjectID,
		&i.IdpProviderName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, status, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Activated,
		&i.AvatarUrl,
		&i.IdpSubjectID,
		&i.IdpProviderName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, status, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Activated,
		&i.AvatarUrl,
		&i.IdpSubjectID,
		&i.IdpProviderName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET
  deleted_at = $2
WHERE id = $1
`

type SoftDeleteUserParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.DeletedAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  display_name = $2,
  email = $3,
  activated = $4,
  avatar_url = $5,
  idp_subject_id = $6,
  idp_provider_name = $7,
  status = $8,
  updated_at = $9,
  deleted_at = $10
WHERE id = $1
RETURNING id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, status, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	Email           string             `db:"email" json:"email"`
	Activated       bool               `db:"activated" json:"activated"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	IdpSubjectID    string             `db:"idp_subject_id" json:"idp_subject_id"`
	IdpProviderName string             `db:"idp_provider_name" json:"idp_provider_name"`
	Status          UsersStatus        `db:"status" json:"status"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Activated,
		arg.AvatarUrl,
		arg.IdpSubjectID,
		arg.IdpProviderName,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Activated,
		&i.AvatarUrl,
		&i.IdpSubjectID,
		&i.IdpProviderName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
