// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO shopping_write.lists (
  id, name, status, shopping_date, owner_party_id, shop_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, status, shopping_date, owner_party_id, shop_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateListParams struct {
	ID           pgtype.UUID              `db:"id" json:"id"`
	Name         pgtype.Text              `db:"name" json:"name"`
	Status       ShoppingWriteListsStatus `db:"status" json:"status"`
	ShoppingDate pgtype.Date              `db:"shopping_date" json:"shopping_date"`
	OwnerPartyID pgtype.UUID              `db:"owner_party_id" json:"owner_party_id"`
	ShopID       pgtype.UUID              `db:"shop_id" json:"shop_id"`
	CreatedAt    pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	CreatedBy    string                   `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (ShoppingWriteList, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.ShoppingDate,
		arg.OwnerPartyID,
		arg.ShopID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i ShoppingWriteList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ShoppingDate,
		&i.OwnerPartyID,
		&i.ShopID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getListByID = `-- name: GetListByID :one
SELECT id, name, status, shopping_date, owner_party_id, shop_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM shopping_write.lists
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetListByID(ctx context.Context, id pgtype.UUID) (ShoppingWriteList, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i ShoppingWriteList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ShoppingDate,
		&i.OwnerPartyID,
		&i.ShopID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteList = `-- name: SoftDeleteList :exec
UPDATE shopping_write.lists SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteListParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteList(ctx context.Context, arg SoftDeleteListParams) error {
	_, err := q.db.Exec(ctx, softDeleteList, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateList = `-- name: UpdateList :one
UPDATE shopping_write.lists SET
  name = $2,
  status = $3,
  shopping_date = $4,
  owner_party_id = $5,
  shop_id = $6,
  updated_at = $7,
  updated_by = $8,
  deleted_at = $9,
  deleted_by = $10
WHERE id = $1
RETURNING id, name, status, shopping_date, owner_party_id, shop_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateListParams struct {
	ID           pgtype.UUID              `db:"id" json:"id"`
	Name         pgtype.Text              `db:"name" json:"name"`
	Status       ShoppingWriteListsStatus `db:"status" json:"status"`
	ShoppingDate pgtype.Date              `db:"shopping_date" json:"shopping_date"`
	OwnerPartyID pgtype.UUID              `db:"owner_party_id" json:"owner_party_id"`
	ShopID       pgtype.UUID              `db:"shop_id" json:"shop_id"`
	UpdatedAt    pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (ShoppingWriteList, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.ShoppingDate,
		arg.OwnerPartyID,
		arg.ShopID,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i ShoppingWriteList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ShoppingDate,
		&i.OwnerPartyID,
		&i.ShopID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
