// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ShoppingWriteListsStatus string

const (
	ShoppingWriteListsStatusDraft     ShoppingWriteListsStatus = "draft"
	ShoppingWriteListsStatusReady     ShoppingWriteListsStatus = "ready"
	ShoppingWriteListsStatusActive    ShoppingWriteListsStatus = "active"
	ShoppingWriteListsStatusCompleted ShoppingWriteListsStatus = "completed"
	ShoppingWriteListsStatusDiscarded ShoppingWriteListsStatus = "discarded"
)

func (e *ShoppingWriteListsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingWriteListsStatus(s)
	case string:
		*e = ShoppingWriteListsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingWriteListsStatus: %T", src)
	}
	return nil
}

type NullShoppingWriteListsStatus struct {
	ShoppingWriteListsStatus ShoppingWriteListsStatus `json:"shopping_write_lists_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if ShoppingWriteListsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingWriteListsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingWriteListsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingWriteListsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingWriteListsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingWriteListsStatus), nil
}

type ShoppingWriteOutboxArchiveStatus string

const (
	ShoppingWriteOutboxArchiveStatusSuccess ShoppingWriteOutboxArchiveStatus = "success"
	ShoppingWriteOutboxArchiveStatusFailed  ShoppingWriteOutboxArchiveStatus = "failed"
)

func (e *ShoppingWriteOutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingWriteOutboxArchiveStatus(s)
	case string:
		*e = ShoppingWriteOutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingWriteOutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullShoppingWriteOutboxArchiveStatus struct {
	ShoppingWriteOutboxArchiveStatus ShoppingWriteOutboxArchiveStatus `json:"shopping_write_outbox_archive_status"`
	Valid                            bool                             `json:"valid"` // Valid is true if ShoppingWriteOutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingWriteOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingWriteOutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingWriteOutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingWriteOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingWriteOutboxArchiveStatus), nil
}

type ShoppingWriteOutboxEventStatus string

const (
	ShoppingWriteOutboxEventStatusPending    ShoppingWriteOutboxEventStatus = "pending"
	ShoppingWriteOutboxEventStatusProcessing ShoppingWriteOutboxEventStatus = "processing"
	ShoppingWriteOutboxEventStatusFailed     ShoppingWriteOutboxEventStatus = "failed"
)

func (e *ShoppingWriteOutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingWriteOutboxEventStatus(s)
	case string:
		*e = ShoppingWriteOutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingWriteOutboxEventStatus: %T", src)
	}
	return nil
}

type NullShoppingWriteOutboxEventStatus struct {
	ShoppingWriteOutboxEventStatus ShoppingWriteOutboxEventStatus `json:"shopping_write_outbox_event_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if ShoppingWriteOutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingWriteOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingWriteOutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingWriteOutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingWriteOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingWriteOutboxEventStatus), nil
}

type ShoppingWriteShopsStatus string

const (
	ShoppingWriteShopsStatusInactive ShoppingWriteShopsStatus = "inactive"
	ShoppingWriteShopsStatusActive   ShoppingWriteShopsStatus = "active"
)

func (e *ShoppingWriteShopsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingWriteShopsStatus(s)
	case string:
		*e = ShoppingWriteShopsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingWriteShopsStatus: %T", src)
	}
	return nil
}

type NullShoppingWriteShopsStatus struct {
	ShoppingWriteShopsStatus ShoppingWriteShopsStatus `json:"shopping_write_shops_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if ShoppingWriteShopsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingWriteShopsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingWriteShopsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingWriteShopsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingWriteShopsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingWriteShopsStatus), nil
}

type ShoppingReadViewShop struct {
	ShopID            pgtype.UUID        `db:"shop_id" json:"shop_id"`
	ShopName          string             `db:"shop_name" json:"shop_name"`
	Status            string             `db:"status" json:"status"`
	Provider          string             `db:"provider" json:"provider"`
	PlaceID           pgtype.Text        `db:"place_id" json:"place_id"`
	PlaceUrl          pgtype.Text        `db:"place_url" json:"place_url"`
	Latitude          pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric     `db:"longitude" json:"longitude"`
	FormattedAddress  string             `db:"formatted_address" json:"formatted_address"`
	AddressComponents []byte             `db:"address_components" json:"address_components"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ShoppingReadViewShoppingList struct {
	ListID       pgtype.UUID        `db:"list_id" json:"list_id"`
	ListName     pgtype.Text        `db:"list_name" json:"list_name"`
	Status       string             `db:"status" json:"status"`
	Items        []byte             `db:"items" json:"items"`
	ShoppingDate pgtype.Date        `db:"shopping_date" json:"shopping_date"`
	ShopID       pgtype.UUID        `db:"shop_id" json:"shop_id"`
	ShopName     pgtype.Text        `db:"shop_name" json:"shop_name"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ShoppingWriteIdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ShoppingWriteItem struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	ListID     pgtype.UUID        `db:"list_id" json:"list_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	IsTicked   bool               `db:"is_ticked" json:"is_ticked"`
	Quantity   int32              `db:"quantity" json:"quantity"`
	Reason     pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type ShoppingWriteList struct {
	ID           pgtype.UUID              `db:"id" json:"id"`
	Name         pgtype.Text              `db:"name" json:"name"`
	Status       ShoppingWriteListsStatus `db:"status" json:"status"`
	ShoppingDate pgtype.Date              `db:"shopping_date" json:"shopping_date"`
	OwnerPartyID pgtype.UUID              `db:"owner_party_id" json:"owner_party_id"`
	ShopID       pgtype.UUID              `db:"shop_id" json:"shop_id"`
	CreatedAt    pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	CreatedBy    string                   `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

type ShoppingWriteOutboxArchive struct {
	ID             pgtype.UUID                      `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID                      `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID                      `db:"trace_id" json:"trace_id"`
	Event          string                           `db:"event" json:"event"`
	Payload        []byte                           `db:"payload" json:"payload"`
	Status         ShoppingWriteOutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32                            `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz               `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz               `db:"archived_at" json:"archived_at"`
}

type ShoppingWriteOutboxEvent struct {
	ID         pgtype.UUID                    `db:"id" json:"id"`
	TraceID    pgtype.UUID                    `db:"trace_id" json:"trace_id"`
	Event      string                         `db:"event" json:"event"`
	Payload    []byte                         `db:"payload" json:"payload"`
	Status     ShoppingWriteOutboxEventStatus `db:"status" json:"status"`
	RetryCount int32                          `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz             `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz             `db:"updated_at" json:"updated_at"`
}

type ShoppingWriteProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type ShoppingWriteShop struct {
	ID                pgtype.UUID              `db:"id" json:"id"`
	Name              string                   `db:"name" json:"name"`
	Status            ShoppingWriteShopsStatus `db:"status" json:"status"`
	Provider          string                   `db:"provider" json:"provider"`
	PlaceID           pgtype.Text              `db:"place_id" json:"place_id"`
	PlaceUrl          pgtype.Text              `db:"place_url" json:"place_url"`
	Latitude          pgtype.Numeric           `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric           `db:"longitude" json:"longitude"`
	FormattedAddress  string                   `db:"formatted_address" json:"formatted_address"`
	AddressComponents []byte                   `db:"address_components" json:"address_components"`
	CreatedAt         pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	CreatedBy         string                   `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy         pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt         pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy         pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}
