// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shopping_write.shops (
  id, name, status, provider, place_id, place_url, latitude, longitude, formatted_address, address_components, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, name, status, provider, place_id, place_url, latitude, longitude, formatted_address, address_components, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateShopParams struct {
	ID                pgtype.UUID              `db:"id" json:"id"`
	Name              string                   `db:"name" json:"name"`
	Status            ShoppingWriteShopsStatus `db:"status" json:"status"`
	Provider          string                   `db:"provider" json:"provider"`
	PlaceID           pgtype.Text              `db:"place_id" json:"place_id"`
	PlaceUrl          pgtype.Text              `db:"place_url" json:"place_url"`
	Latitude          pgtype.Numeric           `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric           `db:"longitude" json:"longitude"`
	FormattedAddress  string                   `db:"formatted_address" json:"formatted_address"`
	AddressComponents []byte                   `db:"address_components" json:"address_components"`
	CreatedAt         pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	CreatedBy         string                   `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy         pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt         pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy         pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (ShoppingWriteShop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Provider,
		arg.PlaceID,
		arg.PlaceUrl,
		arg.Latitude,
		arg.Longitude,
		arg.FormattedAddress,
		arg.AddressComponents,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i ShoppingWriteShop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Provider,
		&i.PlaceID,
		&i.PlaceUrl,
		&i.Latitude,
		&i.Longitude,
		&i.FormattedAddress,
		&i.AddressComponents,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, name, status, provider, place_id, place_url, latitude, longitude, formatted_address, address_components, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM shopping_write.shops
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetShopByID(ctx context.Context, id pgtype.UUID) (ShoppingWriteShop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i ShoppingWriteShop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Provider,
		&i.PlaceID,
		&i.PlaceUrl,
		&i.Latitude,
		&i.Longitude,
		&i.FormattedAddress,
		&i.AddressComponents,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteShop = `-- name: SoftDeleteShop :exec
UPDATE shopping_write.shops SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteShopParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteShop(ctx context.Context, arg SoftDeleteShopParams) error {
	_, err := q.db.Exec(ctx, softDeleteShop, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateShop = `-- name: UpdateShop :one
UPDATE shopping_write.shops SET
  name = $2,
  status = $3,
  provider = $4,
  place_id = $5,
  place_url = $6,
  latitude = $7,
  longitude = $8,
  formatted_address = $9,
  address_components = $10,
  updated_at = $11,
  updated_by = $12,
  deleted_at = $13,
  deleted_by = $14
WHERE id = $1
RETURNING id, name, status, provider, place_id, place_url, latitude, longitude, formatted_address, address_components, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateShopParams struct {
	ID                pgtype.UUID              `db:"id" json:"id"`
	Name              string                   `db:"name" json:"name"`
	Status            ShoppingWriteShopsStatus `db:"status" json:"status"`
	Provider          string                   `db:"provider" json:"provider"`
	PlaceID           pgtype.Text              `db:"place_id" json:"place_id"`
	PlaceUrl          pgtype.Text              `db:"place_url" json:"place_url"`
	Latitude          pgtype.Numeric           `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric           `db:"longitude" json:"longitude"`
	FormattedAddress  string                   `db:"formatted_address" json:"formatted_address"`
	AddressComponents []byte                   `db:"address_components" json:"address_components"`
	UpdatedAt         pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy         pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt         pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy         pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (ShoppingWriteShop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Provider,
		arg.PlaceID,
		arg.PlaceUrl,
		arg.Latitude,
		arg.Longitude,
		arg.FormattedAddress,
		arg.AddressComponents,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i ShoppingWriteShop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Provider,
		&i.PlaceID,
		&i.PlaceUrl,
		&i.Latitude,
		&i.Longitude,
		&i.FormattedAddress,
		&i.AddressComponents,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
