// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_shopping_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewShoppingListByID = `-- name: GetViewShoppingListByID :one
SELECT list_id, list_name, status, items, shopping_date, shop_id, shop_name, owner_party_id, created_at, updated_at, deleted_at FROM shopping_read.view_shopping_list
WHERE list_id = $1
`

func (q *Queries) GetViewShoppingListByID(ctx context.Context, listID pgtype.UUID) (ShoppingReadViewShoppingList, error) {
	row := q.db.QueryRow(ctx, getViewShoppingListByID, listID)
	var i ShoppingReadViewShoppingList
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.Status,
		&i.Items,
		&i.ShoppingDate,
		&i.ShopID,
		&i.ShopName,
		&i.OwnerPartyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listViewShoppingLists = `-- name: ListViewShoppingLists :many
SELECT list_id, list_name, status, items, shopping_date, shop_id, shop_name, owner_party_id, created_at, updated_at, deleted_at FROM shopping_read.view_shopping_list
WHERE ($1::timestamptz IS NULL OR (created_at, list_id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, list_id DESC
LIMIT $3
`

type ListViewShoppingListsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewShoppingLists(ctx context.Context, arg ListViewShoppingListsParams) ([]ShoppingReadViewShoppingList, error) {
	rows, err := q.db.Query(ctx, listViewShoppingLists, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShoppingReadViewShoppingList{}
	for rows.Next() {
		var i ShoppingReadViewShoppingList
		if err := rows.Scan(
			&i.ListID,
			&i.ListName,
			&i.Status,
			&i.Items,
			&i.ShoppingDate,
			&i.ShopID,
			&i.ShopName,
			&i.OwnerPartyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
