// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_messages.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInboxMessage = `-- name: CreateInboxMessage :one
INSERT INTO inbox_messages (id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateInboxMessageParams struct {
	ID        pgtype.UUID         `db:"id" json:"id"`
	UserID    pgtype.UUID         `db:"user_id" json:"user_id"`
	Name      string              `db:"name" json:"name"`
	Status    InboxMessagesStatus `db:"status" json:"status"`
	Title     string              `db:"title" json:"title"`
	Content   string              `db:"content" json:"content"`
	LinkUrl   pgtype.Text         `db:"link_url" json:"link_url"`
	CreatedAt pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	CreatedBy string              `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text         `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz  `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text         `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, createInboxMessage,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Status,
		arg.Title,
		arg.Content,
		arg.LinkUrl,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.LinkUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getInboxMessageById = `-- name: GetInboxMessageById :one
SELECT id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM inbox_messages
WHERE id = $1
`

func (q *Queries) GetInboxMessageById(ctx context.Context, id pgtype.UUID) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, getInboxMessageById, id)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.LinkUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteInboxMessage = `-- name: SoftDeleteInboxMessage :exec
UPDATE inbox_messages SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
RETURNING id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type SoftDeleteInboxMessageParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteInboxMessage(ctx context.Context, arg SoftDeleteInboxMessageParams) error {
	_, err := q.db.Exec(ctx, softDeleteInboxMessage, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateInboxMessage = `-- name: UpdateInboxMessage :one
UPDATE inbox_messages SET
  name = $2,
  status = $3,
  title = $4,
  content = $5,
  link_url = $6,
  updated_at = $7,
  updated_by = $8
WHERE id = $1
RETURNING id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateInboxMessageParams struct {
	ID        pgtype.UUID         `db:"id" json:"id"`
	Name      string              `db:"name" json:"name"`
	Status    InboxMessagesStatus `db:"status" json:"status"`
	Title     string              `db:"title" json:"title"`
	Content   string              `db:"content" json:"content"`
	LinkUrl   pgtype.Text         `db:"link_url" json:"link_url"`
	UpdatedAt pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text         `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateInboxMessage(ctx context.Context, arg UpdateInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, updateInboxMessage,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Title,
		arg.Content,
		arg.LinkUrl,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.LinkUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
