// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InboxMessagesStatus string

const (
	InboxMessagesStatusUnread InboxMessagesStatus = "unread"
	InboxMessagesStatusRead   InboxMessagesStatus = "read"
)

func (e *InboxMessagesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxMessagesStatus(s)
	case string:
		*e = InboxMessagesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxMessagesStatus: %T", src)
	}
	return nil
}

type NullInboxMessagesStatus struct {
	InboxMessagesStatus InboxMessagesStatus `json:"inbox_messages_status"`
	Valid               bool                `json:"valid"` // Valid is true if InboxMessagesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxMessagesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InboxMessagesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxMessagesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxMessagesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxMessagesStatus), nil
}

type OutboxArchiveStatus string

const (
	OutboxArchiveStatusSuccess OutboxArchiveStatus = "success"
	OutboxArchiveStatusFailed  OutboxArchiveStatus = "failed"
)

func (e *OutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxArchiveStatus(s)
	case string:
		*e = OutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullOutboxArchiveStatus struct {
	OutboxArchiveStatus OutboxArchiveStatus `json:"outbox_archive_status"`
	Valid               bool                `json:"valid"` // Valid is true if OutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxArchiveStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type IdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InboxMessage struct {
	ID        pgtype.UUID         `db:"id" json:"id"`
	UserID    pgtype.UUID         `db:"user_id" json:"user_id"`
	Name      string              `db:"name" json:"name"`
	Status    InboxMessagesStatus `db:"status" json:"status"`
	Title     string              `db:"title" json:"title"`
	Content   string              `db:"content" json:"content"`
	LinkUrl   pgtype.Text         `db:"link_url" json:"link_url"`
	CreatedAt pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	CreatedBy string              `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text         `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz  `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text         `db:"deleted_by" json:"deleted_by"`
}

type OutboxArchive struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID         `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID         `db:"trace_id" json:"trace_id"`
	Event          string              `db:"event" json:"event"`
	Payload        []byte              `db:"payload" json:"payload"`
	Status         OutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32               `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz  `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz  `db:"archived_at" json:"archived_at"`
}

type OutboxEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TraceID    pgtype.UUID        `db:"trace_id" json:"trace_id"`
	Event      string             `db:"event" json:"event"`
	Payload    []byte             `db:"payload" json:"payload"`
	Status     OutboxEventStatus  `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}
