// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) (InboxMessage, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (OutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (ProcessedMessage, error)
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (IdempotencyKey, error)
	GetInboxMessageById(ctx context.Context, id pgtype.UUID) (InboxMessage, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]OutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (ProcessedMessage, error)
	SoftDeleteInboxMessage(ctx context.Context, arg SoftDeleteInboxMessageParams) error
	UpdateInboxMessage(ctx context.Context, arg UpdateInboxMessageParams) (InboxMessage, error)
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (OutboxEvent, error)
}

var _ Querier = (*Queries)(nil)
