// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewParty struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Members   []byte             `db:"members" json:"members"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ViewUser struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	Email           string             `db:"email" json:"email"`
	Activated       bool               `db:"activated" json:"activated"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	IdpSubjectID    string             `db:"idp_subject_id" json:"idp_subject_id"`
	IdpProviderName string             `db:"idp_provider_name" json:"idp_provider_name"`
	Parties         []byte             `db:"parties" json:"parties"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
