// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetViewPartyByID(ctx context.Context, id pgtype.UUID) (ViewParty, error)
	GetViewUserByID(ctx context.Context, id pgtype.UUID) (ViewUser, error)
	ListViewParties(ctx context.Context, arg ListViewPartiesParams) ([]ViewParty, error)
	ListViewUsers(ctx context.Context, arg ListViewUsersParams) ([]ViewUser, error)
}

var _ Querier = (*Queries)(nil)
