// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_users.sql

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewUserByID = `-- name: GetViewUserByID :one
SELECT id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, parties, status, created_at, updated_at FROM view_users
WHERE id = $1
`

func (q *Queries) GetViewUserByID(ctx context.Context, id pgtype.UUID) (ViewUser, error) {
	row := q.db.QueryRow(ctx, getViewUserByID, id)
	var i ViewUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Activated,
		&i.AvatarUrl,
		&i.IdpSubjectID,
		&i.IdpProviderName,
		&i.Parties,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewUsers = `-- name: ListViewUsers :many
SELECT id, display_name, email, activated, avatar_url, idp_subject_id, idp_provider_name, parties, status, created_at, updated_at FROM view_users
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListViewUsersParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewUsers(ctx context.Context, arg ListViewUsersParams) ([]ViewUser, error) {
	rows, err := q.db.Query(ctx, listViewUsers, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewUser{}
	for rows.Next() {
		var i ViewUser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.Activated,
			&i.AvatarUrl,
			&i.IdpSubjectID,
			&i.IdpProviderName,
			&i.Parties,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
