// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_parties.sql

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewPartyByID = `-- name: GetViewPartyByID :one
SELECT id, name, members, created_at, updated_at FROM view_parties
WHERE id = $1
`

func (q *Queries) GetViewPartyByID(ctx context.Context, id pgtype.UUID) (ViewParty, error) {
	row := q.db.QueryRow(ctx, getViewPartyByID, id)
	var i ViewParty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Members,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewParties = `-- name: ListViewParties :many
SELECT id, name, members, created_at, updated_at FROM view_parties
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListViewPartiesParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewParties(ctx context.Context, arg ListViewPartiesParams) ([]ViewParty, error) {
	rows, err := q.db.Query(ctx, listViewParties, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewParty{}
	for rows.Next() {
		var i ViewParty
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Members,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
