// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewBrand struct {
	BrandID      pgtype.UUID        `db:"brand_id" json:"brand_id"`
	BrandName    string             `db:"brand_name" json:"brand_name"`
	Status       string             `db:"status" json:"status"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility   string             `db:"visibility" json:"visibility"`
	Tags         []byte             `db:"tags" json:"tags"`
	ProductCount int32              `db:"product_count" json:"product_count"`
	TagCount     int32              `db:"tag_count" json:"tag_count"`
	LogoUrl      pgtype.Text        `db:"logo_url" json:"logo_url"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ViewCategory struct {
	CategoryID   pgtype.UUID        `db:"category_id" json:"category_id"`
	CategoryName string             `db:"category_name" json:"category_name"`
	Status       string             `db:"status" json:"status"`
	Parent       []byte             `db:"parent" json:"parent"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ViewProduct struct {
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	Status          string             `db:"status" json:"status"`
	OwnerID         pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility      string             `db:"visibility" json:"visibility"`
	Brands          []byte             `db:"brands" json:"brands"`
	Categories      []byte             `db:"categories" json:"categories"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetValue        pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit         string             `db:"net_unit" json:"net_unit"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	Nutriscore      pgtype.Text        `db:"nutriscore" json:"nutriscore"`
	NovaGroup       pgtype.Int4        `db:"nova_group" json:"nova_group"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
