// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetViewBrandByID(ctx context.Context, brandID pgtype.UUID) (ViewBrand, error)
	GetViewCategoryByID(ctx context.Context, categoryID pgtype.UUID) (ViewCategory, error)
	GetViewProductByBarcode(ctx context.Context, barcode pgtype.Text) (ViewProduct, error)
	GetViewProductByID(ctx context.Context, productID pgtype.UUID) (ViewProduct, error)
	ListViewBrands(ctx context.Context, arg ListViewBrandsParams) ([]ViewBrand, error)
	ListViewCategories(ctx context.Context, arg ListViewCategoriesParams) ([]ViewCategory, error)
	ListViewProducts(ctx context.Context, arg ListViewProductsParams) ([]ViewProduct, error)
	SearchViewProducts(ctx context.Context, arg SearchViewProductsParams) ([]ViewProduct, error)
}

var _ Querier = (*Queries)(nil)
