// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_brands.sql

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewBrandByID = `-- name: GetViewBrandByID :one
SELECT brand_id, brand_name, status, owner_id, visibility, tags, product_count, tag_count, logo_url, created_at, updated_at FROM view_brands
WHERE brand_id = $1
`

func (q *Queries) GetViewBrandByID(ctx context.Context, brandID pgtype.UUID) (ViewBrand, error) {
	row := q.db.QueryRow(ctx, getViewBrandByID, brandID)
	var i ViewBrand
	err := row.Scan(
		&i.BrandID,
		&i.BrandName,
		&i.Status,
		&i.OwnerID,
		&i.Visibility,
		&i.Tags,
		&i.ProductCount,
		&i.TagCount,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewBrands = `-- name: ListViewBrands :many
SELECT brand_id, brand_name, status, owner_id, visibility, tags, product_count, tag_count, logo_url, created_at, updated_at FROM view_brands
WHERE ($1::timestamptz IS NULL OR (created_at, brand_id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, brand_id DESC
LIMIT $3
`

type ListViewBrandsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewBrands(ctx context.Context, arg ListViewBrandsParams) ([]ViewBrand, error) {
	rows, err := q.db.Query(ctx, listViewBrands, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewBrand{}
	for rows.Next() {
		var i ViewBrand
		if err := rows.Scan(
			&i.BrandID,
			&i.BrandName,
			&i.Status,
			&i.OwnerID,
			&i.Visibility,
			&i.Tags,
			&i.ProductCount,
			&i.TagCount,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
