// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogWriteBrandStatus string

const (
	CatalogWriteBrandStatusInactive CatalogWriteBrandStatus = "inactive"
	CatalogWriteBrandStatusActive   CatalogWriteBrandStatus = "active"
	CatalogWriteBrandStatusArchived CatalogWriteBrandStatus = "archived"
)

func (e *CatalogWriteBrandStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteBrandStatus(s)
	case string:
		*e = CatalogWriteBrandStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteBrandStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteBrandStatus struct {
	CatalogWriteBrandStatus CatalogWriteBrandStatus `json:"catalog_write_brand_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if CatalogWriteBrandStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteBrandStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteBrandStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteBrandStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteBrandStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteBrandStatus), nil
}

type CatalogWriteBrandVisibility string

const (
	CatalogWriteBrandVisibilityOfficial  CatalogWriteBrandVisibility = "official"
	CatalogWriteBrandVisibilityCommunity CatalogWriteBrandVisibility = "community"
	CatalogWriteBrandVisibilityPrivate   CatalogWriteBrandVisibility = "private"
)

func (e *CatalogWriteBrandVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteBrandVisibility(s)
	case string:
		*e = CatalogWriteBrandVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteBrandVisibility: %T", src)
	}
	return nil
}

type NullCatalogWriteBrandVisibility struct {
	CatalogWriteBrandVisibility CatalogWriteBrandVisibility `json:"catalog_write_brand_visibility"`
	Valid                       bool                        `json:"valid"` // Valid is true if CatalogWriteBrandVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteBrandVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteBrandVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteBrandVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteBrandVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteBrandVisibility), nil
}

type CatalogWriteCategoryStatus string

const (
	CatalogWriteCategoryStatusInactive CatalogWriteCategoryStatus = "inactive"
	CatalogWriteCategoryStatusActive   CatalogWriteCategoryStatus = "active"
	CatalogWriteCategoryStatusArchived CatalogWriteCategoryStatus = "archived"
)

func (e *CatalogWriteCategoryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteCategoryStatus(s)
	case string:
		*e = CatalogWriteCategoryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteCategoryStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteCategoryStatus struct {
	CatalogWriteCategoryStatus CatalogWriteCategoryStatus `json:"catalog_write_category_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if CatalogWriteCategoryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteCategoryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteCategoryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteCategoryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteCategoryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteCategoryStatus), nil
}

type CatalogWriteOutboxArchiveStatus string

const (
	CatalogWriteOutboxArchiveStatusSuccess CatalogWriteOutboxArchiveStatus = "success"
	CatalogWriteOutboxArchiveStatusFailed  CatalogWriteOutboxArchiveStatus = "failed"
)

func (e *CatalogWriteOutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteOutboxArchiveStatus(s)
	case string:
		*e = CatalogWriteOutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteOutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteOutboxArchiveStatus struct {
	CatalogWriteOutboxArchiveStatus CatalogWriteOutboxArchiveStatus `json:"catalog_write_outbox_archive_status"`
	Valid                           bool                            `json:"valid"` // Valid is true if CatalogWriteOutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteOutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteOutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteOutboxArchiveStatus), nil
}

type CatalogWriteOutboxEventStatus string

const (
	CatalogWriteOutboxEventStatusPending    CatalogWriteOutboxEventStatus = "pending"
	CatalogWriteOutboxEventStatusProcessing CatalogWriteOutboxEventStatus = "processing"
	CatalogWriteOutboxEventStatusFailed     CatalogWriteOutboxEventStatus = "failed"
)

func (e *CatalogWriteOutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteOutboxEventStatus(s)
	case string:
		*e = CatalogWriteOutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteOutboxEventStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteOutboxEventStatus struct {
	CatalogWriteOutboxEventStatus CatalogWriteOutboxEventStatus `json:"catalog_write_outbox_event_status"`
	Valid                         bool                          `json:"valid"` // Valid is true if CatalogWriteOutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteOutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteOutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteOutboxEventStatus), nil
}

type CatalogWriteProductNetUnit string

const (
	CatalogWriteProductNetUnitG  CatalogWriteProductNetUnit = "g"
	CatalogWriteProductNetUnitKg CatalogWriteProductNetUnit = "kg"
	CatalogWriteProductNetUnitMl CatalogWriteProductNetUnit = "ml"
	CatalogWriteProductNetUnitL  CatalogWriteProductNetUnit = "l"
)

func (e *CatalogWriteProductNetUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteProductNetUnit(s)
	case string:
		*e = CatalogWriteProductNetUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteProductNetUnit: %T", src)
	}
	return nil
}

type NullCatalogWriteProductNetUnit struct {
	CatalogWriteProductNetUnit CatalogWriteProductNetUnit `json:"catalog_write_product_net_unit"`
	Valid                      bool                       `json:"valid"` // Valid is true if CatalogWriteProductNetUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteProductNetUnit) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteProductNetUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteProductNetUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteProductNetUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteProductNetUnit), nil
}

type CatalogWriteProductStatus string

const (
	CatalogWriteProductStatusInactive CatalogWriteProductStatus = "inactive"
	CatalogWriteProductStatusActive   CatalogWriteProductStatus = "active"
	CatalogWriteProductStatusArchived CatalogWriteProductStatus = "archived"
)

func (e *CatalogWriteProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteProductStatus(s)
	case string:
		*e = CatalogWriteProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteProductStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteProductStatus struct {
	CatalogWriteProductStatus CatalogWriteProductStatus `json:"catalog_write_product_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if CatalogWriteProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteProductStatus), nil
}

type CatalogWriteProductVisibility string

const (
	CatalogWriteProductVisibilityOfficial  CatalogWriteProductVisibility = "official"
	CatalogWriteProductVisibilityCommunity CatalogWriteProductVisibility = "community"
	CatalogWriteProductVisibilityPrivate   CatalogWriteProductVisibility = "private"
)

func (e *CatalogWriteProductVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteProductVisibility(s)
	case string:
		*e = CatalogWriteProductVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteProductVisibility: %T", src)
	}
	return nil
}

type NullCatalogWriteProductVisibility struct {
	CatalogWriteProductVisibility CatalogWriteProductVisibility `json:"catalog_write_product_visibility"`
	Valid                         bool                          `json:"valid"` // Valid is true if CatalogWriteProductVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteProductVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteProductVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteProductVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteProductVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteProductVisibility), nil
}

type CatalogWriteProviderRawDataStatus string

const (
	CatalogWriteProviderRawDataStatusPending   CatalogWriteProviderRawDataStatus = "pending"
	CatalogWriteProviderRawDataStatusProcessed CatalogWriteProviderRawDataStatus = "processed"
	CatalogWriteProviderRawDataStatusFailed    CatalogWriteProviderRawDataStatus = "failed"
)

func (e *CatalogWriteProviderRawDataStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteProviderRawDataStatus(s)
	case string:
		*e = CatalogWriteProviderRawDataStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteProviderRawDataStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteProviderRawDataStatus struct {
	CatalogWriteProviderRawDataStatus CatalogWriteProviderRawDataStatus `json:"catalog_write_provider_raw_data_status"`
	Valid                             bool                              `json:"valid"` // Valid is true if CatalogWriteProviderRawDataStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteProviderRawDataStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteProviderRawDataStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteProviderRawDataStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteProviderRawDataStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteProviderRawDataStatus), nil
}

type CatalogWriteProviderStatus string

const (
	CatalogWriteProviderStatusInactive CatalogWriteProviderStatus = "inactive"
	CatalogWriteProviderStatusActive   CatalogWriteProviderStatus = "active"
	CatalogWriteProviderStatusArchived CatalogWriteProviderStatus = "archived"
)

func (e *CatalogWriteProviderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogWriteProviderStatus(s)
	case string:
		*e = CatalogWriteProviderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogWriteProviderStatus: %T", src)
	}
	return nil
}

type NullCatalogWriteProviderStatus struct {
	CatalogWriteProviderStatus CatalogWriteProviderStatus `json:"catalog_write_provider_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if CatalogWriteProviderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogWriteProviderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogWriteProviderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogWriteProviderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogWriteProviderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogWriteProviderStatus), nil
}

type CatalogReadViewBrand struct {
	BrandID      pgtype.UUID        `db:"brand_id" json:"brand_id"`
	BrandName    string             `db:"brand_name" json:"brand_name"`
	Status       string             `db:"status" json:"status"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility   string             `db:"visibility" json:"visibility"`
	Tags         []byte             `db:"tags" json:"tags"`
	ProductCount int32              `db:"product_count" json:"product_count"`
	TagCount     int32              `db:"tag_count" json:"tag_count"`
	LogoUrl      pgtype.Text        `db:"logo_url" json:"logo_url"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogReadViewCategory struct {
	CategoryID   pgtype.UUID        `db:"category_id" json:"category_id"`
	CategoryName string             `db:"category_name" json:"category_name"`
	Status       string             `db:"status" json:"status"`
	Parent       []byte             `db:"parent" json:"parent"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogReadViewProduct struct {
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	Status          string             `db:"status" json:"status"`
	OwnerID         pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility      string             `db:"visibility" json:"visibility"`
	Brands          []byte             `db:"brands" json:"brands"`
	Categories      []byte             `db:"categories" json:"categories"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetValue        pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit         string             `db:"net_unit" json:"net_unit"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	Nutriscore      pgtype.Text        `db:"nutriscore" json:"nutriscore"`
	NovaGroup       pgtype.Int4        `db:"nova_group" json:"nova_group"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogWriteBrand struct {
	ID         pgtype.UUID                 `db:"id" json:"id"`
	Name       string                      `db:"name" json:"name"`
	Status     CatalogWriteBrandStatus     `db:"status" json:"status"`
	LogoUrl    pgtype.Text                 `db:"logo_url" json:"logo_url"`
	OwnerID    pgtype.UUID                 `db:"owner_id" json:"owner_id"`
	Visibility CatalogWriteBrandVisibility `db:"visibility" json:"visibility"`
	CreatedAt  pgtype.Timestamptz          `db:"created_at" json:"created_at"`
	CreatedBy  string                      `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz          `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text                 `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz          `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text                 `db:"deleted_by" json:"deleted_by"`
}

type CatalogWriteBrandTag struct {
	BrandID   pgtype.UUID        `db:"brand_id" json:"brand_id"`
	TagID     pgtype.UUID        `db:"tag_id" json:"tag_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

type CatalogWriteCategory struct {
	ID        pgtype.UUID                `db:"id" json:"id"`
	Status    CatalogWriteCategoryStatus `db:"status" json:"status"`
	Name      string                     `db:"name" json:"name"`
	ParentID  pgtype.UUID                `db:"parent_id" json:"parent_id"`
	CreatedAt pgtype.Timestamptz         `db:"created_at" json:"created_at"`
	CreatedBy string                     `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz         `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text                `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz         `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text                `db:"deleted_by" json:"deleted_by"`
}

type CatalogWriteCategoryTag struct {
	CategoryID pgtype.UUID        `db:"category_id" json:"category_id"`
	TagID      pgtype.UUID        `db:"tag_id" json:"tag_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type CatalogWriteIdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CatalogWriteOutboxArchive struct {
	ID             pgtype.UUID                     `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID                     `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID                     `db:"trace_id" json:"trace_id"`
	Event          string                          `db:"event" json:"event"`
	Payload        []byte                          `db:"payload" json:"payload"`
	Status         CatalogWriteOutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32                           `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz              `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz              `db:"archived_at" json:"archived_at"`
}

type CatalogWriteOutboxEvent struct {
	ID         pgtype.UUID                   `db:"id" json:"id"`
	TraceID    pgtype.UUID                   `db:"trace_id" json:"trace_id"`
	Event      string                        `db:"event" json:"event"`
	Payload    []byte                        `db:"payload" json:"payload"`
	Status     CatalogWriteOutboxEventStatus `db:"status" json:"status"`
	RetryCount int32                         `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz            `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz            `db:"updated_at" json:"updated_at"`
}

type CatalogWriteProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type CatalogWriteProduct struct {
	ID         pgtype.UUID                   `db:"id" json:"id"`
	Status     CatalogWriteProductStatus     `db:"status" json:"status"`
	Name       string                        `db:"name" json:"name"`
	Barcode    pgtype.Text                   `db:"barcode" json:"barcode"`
	NetValue   pgtype.Numeric                `db:"net_value" json:"net_value"`
	NetUnit    CatalogWriteProductNetUnit    `db:"net_unit" json:"net_unit"`
	ImageUrl   pgtype.Text                   `db:"image_url" json:"image_url"`
	Nutriscore pgtype.Text                   `db:"nutriscore" json:"nutriscore"`
	NovaGroup  pgtype.Int4                   `db:"nova_group" json:"nova_group"`
	OwnerID    pgtype.UUID                   `db:"owner_id" json:"owner_id"`
	Visibility CatalogWriteProductVisibility `db:"visibility" json:"visibility"`
	CreatedAt  pgtype.Timestamptz            `db:"created_at" json:"created_at"`
	CreatedBy  string                        `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz            `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text                   `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz            `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text                   `db:"deleted_by" json:"deleted_by"`
}

type CatalogWriteProductBrand struct {
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	BrandID   pgtype.UUID        `db:"brand_id" json:"brand_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

type CatalogWriteProductCategory struct {
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	CategoryID pgtype.UUID        `db:"category_id" json:"category_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type CatalogWriteProductProvider struct {
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type CatalogWriteProvider struct {
	ID         pgtype.UUID                `db:"id" json:"id"`
	Name       string                     `db:"name" json:"name"`
	Status     CatalogWriteProviderStatus `db:"status" json:"status"`
	WebsiteUrl pgtype.Text                `db:"website_url" json:"website_url"`
	LogoUrl    pgtype.Text                `db:"logo_url" json:"logo_url"`
	CreatedAt  pgtype.Timestamptz         `db:"created_at" json:"created_at"`
	CreatedBy  string                     `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz         `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text                `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz         `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text                `db:"deleted_by" json:"deleted_by"`
}

type CatalogWriteProviderRawDatum struct {
	ID          pgtype.UUID                       `db:"id" json:"id"`
	Barcode     pgtype.Text                       `db:"barcode" json:"barcode"`
	Status      CatalogWriteProviderRawDataStatus `db:"status" json:"status"`
	ProviderID  pgtype.UUID                       `db:"provider_id" json:"provider_id"`
	RawData     []byte                            `db:"raw_data" json:"raw_data"`
	FetchedAt   pgtype.Timestamptz                `db:"fetched_at" json:"fetched_at"`
	ProcessedAt pgtype.Timestamptz                `db:"processed_at" json:"processed_at"`
}

type CatalogWriteTag struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}
