// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO catalog_write.product_categories (product_id, category_id, created_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING product_id, category_id, created_at, created_by
`

type CreateProductCategoryParams struct {
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	CategoryID pgtype.UUID        `db:"category_id" json:"category_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (CatalogWriteProductCategory, error) {
	row := q.db.QueryRow(ctx, createProductCategory,
		arg.ProductID,
		arg.CategoryID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i CatalogWriteProductCategory
	err := row.Scan(
		&i.ProductID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const removeProductCategory = `-- name: RemoveProductCategory :exec
DELETE FROM catalog_write.product_categories
WHERE product_id = $1 AND category_id = $2
`

type RemoveProductCategoryParams struct {
	ProductID  pgtype.UUID `db:"product_id" json:"product_id"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
}

func (q *Queries) RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error {
	_, err := q.db.Exec(ctx, removeProductCategory, arg.ProductID, arg.CategoryID)
	return err
}
