// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductProvider = `-- name: CreateProductProvider :one
INSERT INTO catalog_write.product_providers (product_id, provider_id, created_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING product_id, provider_id, created_at, created_by
`

type CreateProductProviderParams struct {
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateProductProvider(ctx context.Context, arg CreateProductProviderParams) (CatalogWriteProductProvider, error) {
	row := q.db.QueryRow(ctx, createProductProvider,
		arg.ProductID,
		arg.ProviderID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i CatalogWriteProductProvider
	err := row.Scan(
		&i.ProductID,
		&i.ProviderID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const removeProductProvider = `-- name: RemoveProductProvider :exec
DELETE FROM catalog_write.product_providers
WHERE product_id = $1 AND provider_id = $2
`

type RemoveProductProviderParams struct {
	ProductID  pgtype.UUID `db:"product_id" json:"product_id"`
	ProviderID pgtype.UUID `db:"provider_id" json:"provider_id"`
}

func (q *Queries) RemoveProductProvider(ctx context.Context, arg RemoveProductProviderParams) error {
	_, err := q.db.Exec(ctx, removeProductProvider, arg.ProductID, arg.ProviderID)
	return err
}
