// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewCategoryByID = `-- name: GetViewCategoryByID :one
SELECT category_id, category_name, status, parent, created_at, updated_at FROM catalog_read.view_categories
WHERE category_id = $1
`

func (q *Queries) GetViewCategoryByID(ctx context.Context, categoryID pgtype.UUID) (CatalogReadViewCategory, error) {
	row := q.db.QueryRow(ctx, getViewCategoryByID, categoryID)
	var i CatalogReadViewCategory
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryName,
		&i.Status,
		&i.Parent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewCategories = `-- name: ListViewCategories :many
SELECT category_id, category_name, status, parent, created_at, updated_at FROM catalog_read.view_categories
WHERE ($1::timestamptz IS NULL OR (created_at, category_id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, category_id DESC
LIMIT $3
`

type ListViewCategoriesParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewCategories(ctx context.Context, arg ListViewCategoriesParams) ([]CatalogReadViewCategory, error) {
	rows, err := q.db.Query(ctx, listViewCategories, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogReadViewCategory{}
	for rows.Next() {
		var i CatalogReadViewCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.Status,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
