// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewProductByBarcode = `-- name: GetViewProductByBarcode :one
SELECT product_id, product_name, barcode, status, owner_id, visibility, brands, categories, quantity_display, net_value, net_unit, image_url, nutriscore, nova_group, created_at, updated_at FROM catalog_read.view_products
WHERE barcode = $1
`

func (q *Queries) GetViewProductByBarcode(ctx context.Context, barcode pgtype.Text) (CatalogReadViewProduct, error) {
	row := q.db.QueryRow(ctx, getViewProductByBarcode, barcode)
	var i CatalogReadViewProduct
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.Barcode,
		&i.Status,
		&i.OwnerID,
		&i.Visibility,
		&i.Brands,
		&i.Categories,
		&i.QuantityDisplay,
		&i.NetValue,
		&i.NetUnit,
		&i.ImageUrl,
		&i.Nutriscore,
		&i.NovaGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getViewProductByID = `-- name: GetViewProductByID :one
SELECT product_id, product_name, barcode, status, owner_id, visibility, brands, categories, quantity_display, net_value, net_unit, image_url, nutriscore, nova_group, created_at, updated_at FROM catalog_read.view_products
WHERE product_id = $1
`

func (q *Queries) GetViewProductByID(ctx context.Context, productID pgtype.UUID) (CatalogReadViewProduct, error) {
	row := q.db.QueryRow(ctx, getViewProductByID, productID)
	var i CatalogReadViewProduct
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.Barcode,
		&i.Status,
		&i.OwnerID,
		&i.Visibility,
		&i.Brands,
		&i.Categories,
		&i.QuantityDisplay,
		&i.NetValue,
		&i.NetUnit,
		&i.ImageUrl,
		&i.Nutriscore,
		&i.NovaGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewProducts = `-- name: ListViewProducts :many
SELECT product_id, product_name, barcode, status, owner_id, visibility, brands, categories, quantity_display, net_value, net_unit, image_url, nutriscore, nova_group, created_at, updated_at FROM catalog_read.view_products
WHERE ($1::timestamptz IS NULL OR (created_at, product_id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, product_id DESC
LIMIT $3
`

type ListViewProductsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewProducts(ctx context.Context, arg ListViewProductsParams) ([]CatalogReadViewProduct, error) {
	rows, err := q.db.Query(ctx, listViewProducts, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogReadViewProduct{}
	for rows.Next() {
		var i CatalogReadViewProduct
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.Barcode,
			&i.Status,
			&i.OwnerID,
			&i.Visibility,
			&i.Brands,
			&i.Categories,
			&i.QuantityDisplay,
			&i.NetValue,
			&i.NetUnit,
			&i.ImageUrl,
			&i.Nutriscore,
			&i.NovaGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchViewProducts = `-- name: SearchViewProducts :many
SELECT product_id, product_name, barcode, status, owner_id, visibility, brands, categories, quantity_display, net_value, net_unit, image_url, nutriscore, nova_group, created_at, updated_at FROM catalog_read.view_products
WHERE (
  (status = 'active' AND visibility IN ('official', 'community'))
  OR (visibility = 'private' AND owner_id = $1::uuid)
)
AND ($2::text IS NULL OR product_name ILIKE '%' || $2::text || '%')
AND ($3::timestamptz IS NULL OR (created_at, product_id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, product_id DESC
LIMIT $5
`

type SearchViewProductsParams struct {
	OwnerID         pgtype.UUID        `db:"owner_id" json:"owner_id"`
	SearchQuery     string             `db:"search_query" json:"search_query"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) SearchViewProducts(ctx context.Context, arg SearchViewProductsParams) ([]CatalogReadViewProduct, error) {
	rows, err := q.db.Query(ctx, searchViewProducts,
		arg.OwnerID,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogReadViewProduct{}
	for rows.Next() {
		var i CatalogReadViewProduct
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.Barcode,
			&i.Status,
			&i.OwnerID,
			&i.Visibility,
			&i.Brands,
			&i.Categories,
			&i.QuantityDisplay,
			&i.NetValue,
			&i.NetUnit,
			&i.ImageUrl,
			&i.Nutriscore,
			&i.NovaGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
