// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewRecipe struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Status       string             `db:"status" json:"status"`
	Instructions []byte             `db:"instructions" json:"instructions"`
	Ingredients  []byte             `db:"ingredients" json:"ingredients"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	Visibility   string             `db:"visibility" json:"visibility"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    string             `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text        `db:"updated_by" json:"updated_by"`
}
