// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetViewRecipeByID(ctx context.Context, id pgtype.UUID) (ViewRecipe, error)
	ListViewRecipes(ctx context.Context, arg ListViewRecipesParams) ([]ViewRecipe, error)
}

var _ Querier = (*Queries)(nil)
