// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_recipes.sql

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewRecipeByID = `-- name: GetViewRecipeByID :one
SELECT id, name, status, instructions, ingredients, owner_id, owner_party_id, visibility, created_at, created_by, updated_at, updated_by FROM view_recipes
WHERE id = $1
`

func (q *Queries) GetViewRecipeByID(ctx context.Context, id pgtype.UUID) (ViewRecipe, error) {
	row := q.db.QueryRow(ctx, getViewRecipeByID, id)
	var i ViewRecipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Instructions,
		&i.Ingredients,
		&i.OwnerID,
		&i.OwnerPartyID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listViewRecipes = `-- name: ListViewRecipes :many
SELECT id, name, status, instructions, ingredients, owner_id, owner_party_id, visibility, created_at, created_by, updated_at, updated_by FROM view_recipes
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListViewRecipesParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewRecipes(ctx context.Context, arg ListViewRecipesParams) ([]ViewRecipe, error) {
	rows, err := q.db.Query(ctx, listViewRecipes, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewRecipe{}
	for rows.Next() {
		var i ViewRecipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Instructions,
			&i.Ingredients,
			&i.OwnerID,
			&i.OwnerPartyID,
			&i.Visibility,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
