// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AreaStatus string

const (
	AreaStatusActive   AreaStatus = "active"
	AreaStatusInactive AreaStatus = "inactive"
)

func (e *AreaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AreaStatus(s)
	case string:
		*e = AreaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AreaStatus: %T", src)
	}
	return nil
}

type NullAreaStatus struct {
	AreaStatus AreaStatus `json:"area_status"`
	Valid      bool       `json:"valid"` // Valid is true if AreaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAreaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AreaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AreaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAreaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AreaStatus), nil
}

type OutboxArchiveStatus string

const (
	OutboxArchiveStatusSuccess OutboxArchiveStatus = "success"
	OutboxArchiveStatusFailed  OutboxArchiveStatus = "failed"
)

func (e *OutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxArchiveStatus(s)
	case string:
		*e = OutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullOutboxArchiveStatus struct {
	OutboxArchiveStatus OutboxArchiveStatus `json:"outbox_archive_status"`
	Valid               bool                `json:"valid"` // Valid is true if OutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxArchiveStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type StockNetUnit string

const (
	StockNetUnitG  StockNetUnit = "g"
	StockNetUnitKg StockNetUnit = "kg"
	StockNetUnitMl StockNetUnit = "ml"
	StockNetUnitL  StockNetUnit = "l"
)

func (e *StockNetUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockNetUnit(s)
	case string:
		*e = StockNetUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for StockNetUnit: %T", src)
	}
	return nil
}

type NullStockNetUnit struct {
	StockNetUnit StockNetUnit `json:"stock_net_unit"`
	Valid        bool         `json:"valid"` // Valid is true if StockNetUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockNetUnit) Scan(value interface{}) error {
	if value == nil {
		ns.StockNetUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockNetUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockNetUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockNetUnit), nil
}

type StockStatus string

const (
	StockStatusAvailable StockStatus = "available"
	StockStatusReserved  StockStatus = "reserved"
	StockStatusOpened    StockStatus = "opened"
	StockStatusExpired   StockStatus = "expired"
	StockStatusConsumed  StockStatus = "consumed"
	StockStatusDiscarded StockStatus = "discarded"
	StockStatusLost      StockStatus = "lost"
)

func (e *StockStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockStatus(s)
	case string:
		*e = StockStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StockStatus: %T", src)
	}
	return nil
}

type NullStockStatus struct {
	StockStatus StockStatus `json:"stock_status"`
	Valid       bool        `json:"valid"` // Valid is true if StockStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StockStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockStatus), nil
}

type StockTransactionsAction string

const (
	StockTransactionsActionAdded     StockTransactionsAction = "added"
	StockTransactionsActionConsumed  StockTransactionsAction = "consumed"
	StockTransactionsActionOpened    StockTransactionsAction = "opened"
	StockTransactionsActionDiscarded StockTransactionsAction = "discarded"
	StockTransactionsActionExpired   StockTransactionsAction = "expired"
	StockTransactionsActionMoved     StockTransactionsAction = "moved"
	StockTransactionsActionCorrected StockTransactionsAction = "corrected"
)

func (e *StockTransactionsAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockTransactionsAction(s)
	case string:
		*e = StockTransactionsAction(s)
	default:
		return fmt.Errorf("unsupported scan type for StockTransactionsAction: %T", src)
	}
	return nil
}

type NullStockTransactionsAction struct {
	StockTransactionsAction StockTransactionsAction `json:"stock_transactions_action"`
	Valid                   bool                    `json:"valid"` // Valid is true if StockTransactionsAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockTransactionsAction) Scan(value interface{}) error {
	if value == nil {
		ns.StockTransactionsAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockTransactionsAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockTransactionsAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockTransactionsAction), nil
}

type Area struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    AreaStatus         `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type IdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxArchive struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID         `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID         `db:"trace_id" json:"trace_id"`
	Event          string              `db:"event" json:"event"`
	Payload        []byte              `db:"payload" json:"payload"`
	Status         OutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32               `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz  `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz  `db:"archived_at" json:"archived_at"`
}

type OutboxEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TraceID    pgtype.UUID        `db:"trace_id" json:"trace_id"`
	Event      string             `db:"event" json:"event"`
	Payload    []byte             `db:"payload" json:"payload"`
	Status     OutboxEventStatus  `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type Stock struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	AreaID          pgtype.UUID        `db:"area_id" json:"area_id"`
	Status          StockStatus        `db:"status" json:"status"`
	OwnerPartyID    pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetValue        pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit         StockNetUnit       `db:"net_unit" json:"net_unit"`
	RemainingValue  pgtype.Numeric     `db:"remaining_value" json:"remaining_value"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy       string             `db:"created_by" json:"created_by"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy       pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy       pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type StockTransaction struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	StockID             pgtype.UUID        `db:"stock_id" json:"stock_id"`
	Action              string             `db:"action" json:"action"`
	DeltaQuantity       int32              `db:"delta_quantity" json:"delta_quantity"`
	DeltaRemainingValue pgtype.Numeric     `db:"delta_remaining_value" json:"delta_remaining_value"`
	Payload             []byte             `db:"payload" json:"payload"`
	OwnerPartyID        pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	ActorID             pgtype.UUID        `db:"actor_id" json:"actor_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy           string             `db:"created_by" json:"created_by"`
}
