// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (OutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (ProcessedMessage, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	CreateStockTransaction(ctx context.Context, arg CreateStockTransactionParams) (StockTransaction, error)
	GetAreaByID(ctx context.Context, id pgtype.UUID) (Area, error)
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (IdempotencyKey, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]OutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (ProcessedMessage, error)
	GetStockByID(ctx context.Context, id pgtype.UUID) (Stock, error)
	GetStockTransactionByID(ctx context.Context, id pgtype.UUID) (StockTransaction, error)
	SoftDeleteArea(ctx context.Context, arg SoftDeleteAreaParams) error
	SoftDeleteStock(ctx context.Context, arg SoftDeleteStockParams) error
	UpdateArea(ctx context.Context, arg UpdateAreaParams) (Area, error)
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (OutboxEvent, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
}

var _ Querier = (*Queries)(nil)
