// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStock = `-- name: CreateStock :one
INSERT INTO stock (
  id, product_id, area_id, status, owner_party_id, quantity, quantity_display, net_value, net_unit, remaining_value, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, product_id, area_id, status, owner_party_id, quantity, quantity_display, net_value, net_unit, remaining_value, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateStockParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	AreaID          pgtype.UUID        `db:"area_id" json:"area_id"`
	Status          StockStatus        `db:"status" json:"status"`
	OwnerPartyID    pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetValue        pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit         StockNetUnit       `db:"net_unit" json:"net_unit"`
	RemainingValue  pgtype.Numeric     `db:"remaining_value" json:"remaining_value"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy       string             `db:"created_by" json:"created_by"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy       pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy       pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, createStock,
		arg.ID,
		arg.ProductID,
		arg.AreaID,
		arg.Status,
		arg.OwnerPartyID,
		arg.Quantity,
		arg.QuantityDisplay,
		arg.NetValue,
		arg.NetUnit,
		arg.RemainingValue,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AreaID,
		&i.Status,
		&i.OwnerPartyID,
		&i.Quantity,
		&i.QuantityDisplay,
		&i.NetValue,
		&i.NetUnit,
		&i.RemainingValue,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getStockByID = `-- name: GetStockByID :one
SELECT id, product_id, area_id, status, owner_party_id, quantity, quantity_display, net_value, net_unit, remaining_value, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM stock
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStockByID(ctx context.Context, id pgtype.UUID) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockByID, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AreaID,
		&i.Status,
		&i.OwnerPartyID,
		&i.Quantity,
		&i.QuantityDisplay,
		&i.NetValue,
		&i.NetUnit,
		&i.RemainingValue,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteStock = `-- name: SoftDeleteStock :exec
UPDATE stock SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteStockParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteStock(ctx context.Context, arg SoftDeleteStockParams) error {
	_, err := q.db.Exec(ctx, softDeleteStock, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateStock = `-- name: UpdateStock :one
UPDATE stock SET
  product_id = $2,
  area_id = $3,
  status = $4,
  owner_party_id = $5,
  quantity = $6,
  quantity_display = $7,
  net_value = $8,
  net_unit = $9,
  remaining_value = $10,
  expires_at = $11,
  updated_at = $12,
  updated_by = $13,
  deleted_at = $14,
  deleted_by = $15
WHERE id = $1
RETURNING id, product_id, area_id, status, owner_party_id, quantity, quantity_display, net_value, net_unit, remaining_value, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateStockParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	AreaID          pgtype.UUID        `db:"area_id" json:"area_id"`
	Status          StockStatus        `db:"status" json:"status"`
	OwnerPartyID    pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetValue        pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit         StockNetUnit       `db:"net_unit" json:"net_unit"`
	RemainingValue  pgtype.Numeric     `db:"remaining_value" json:"remaining_value"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy       pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy       pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, updateStock,
		arg.ID,
		arg.ProductID,
		arg.AreaID,
		arg.Status,
		arg.OwnerPartyID,
		arg.Quantity,
		arg.QuantityDisplay,
		arg.NetValue,
		arg.NetUnit,
		arg.RemainingValue,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AreaID,
		&i.Status,
		&i.OwnerPartyID,
		&i.Quantity,
		&i.QuantityDisplay,
		&i.NetValue,
		&i.NetUnit,
		&i.RemainingValue,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
