// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_transactions.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockTransaction = `-- name: CreateStockTransaction :one
INSERT INTO stock_transactions (
  id, stock_id, action, delta_quantity, delta_remaining_value, payload, owner_party_id, actor_id, created_at, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, stock_id, action, delta_quantity, delta_remaining_value, payload, owner_party_id, actor_id, created_at, created_by
`

type CreateStockTransactionParams struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	StockID             pgtype.UUID        `db:"stock_id" json:"stock_id"`
	Action              string             `db:"action" json:"action"`
	DeltaQuantity       int32              `db:"delta_quantity" json:"delta_quantity"`
	DeltaRemainingValue pgtype.Numeric     `db:"delta_remaining_value" json:"delta_remaining_value"`
	Payload             []byte             `db:"payload" json:"payload"`
	OwnerPartyID        pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	ActorID             pgtype.UUID        `db:"actor_id" json:"actor_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy           string             `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateStockTransaction(ctx context.Context, arg CreateStockTransactionParams) (StockTransaction, error) {
	row := q.db.QueryRow(ctx, createStockTransaction,
		arg.ID,
		arg.StockID,
		arg.Action,
		arg.DeltaQuantity,
		arg.DeltaRemainingValue,
		arg.Payload,
		arg.OwnerPartyID,
		arg.ActorID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i StockTransaction
	err := row.Scan(
		&i.ID,
		&i.StockID,
		&i.Action,
		&i.DeltaQuantity,
		&i.DeltaRemainingValue,
		&i.Payload,
		&i.OwnerPartyID,
		&i.ActorID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getStockTransactionByID = `-- name: GetStockTransactionByID :one
SELECT id, stock_id, action, delta_quantity, delta_remaining_value, payload, owner_party_id, actor_id, created_at, created_by FROM stock_transactions
WHERE id = $1
`

func (q *Queries) GetStockTransactionByID(ctx context.Context, id pgtype.UUID) (StockTransaction, error) {
	row := q.db.QueryRow(ctx, getStockTransactionByID, id)
	var i StockTransaction
	err := row.Scan(
		&i.ID,
		&i.StockID,
		&i.Action,
		&i.DeltaQuantity,
		&i.DeltaRemainingValue,
		&i.Payload,
		&i.OwnerPartyID,
		&i.ActorID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
