// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brand_tags.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrandTag = `-- name: CreateBrandTag :one
INSERT INTO brand_tags (brand_id, tag_id, created_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING brand_id, tag_id, created_at, created_by
`

type CreateBrandTagParams struct {
	BrandID   pgtype.UUID        `db:"brand_id" json:"brand_id"`
	TagID     pgtype.UUID        `db:"tag_id" json:"tag_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateBrandTag(ctx context.Context, arg CreateBrandTagParams) (BrandTag, error) {
	row := q.db.QueryRow(ctx, createBrandTag,
		arg.BrandID,
		arg.TagID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i BrandTag
	err := row.Scan(
		&i.BrandID,
		&i.TagID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const removeBrandTag = `-- name: RemoveBrandTag :exec
DELETE FROM brand_tags
WHERE brand_id = $1 AND tag_id = $2
`

type RemoveBrandTagParams struct {
	BrandID pgtype.UUID `db:"brand_id" json:"brand_id"`
	TagID   pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveBrandTag(ctx context.Context, arg RemoveBrandTagParams) error {
	_, err := q.db.Exec(ctx, removeBrandTag, arg.BrandID, arg.TagID)
	return err
}
