// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (
  id, name, status, logo_url, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, status, logo_url, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateBrandParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     BrandStatus        `db:"status" json:"status"`
	LogoUrl    pgtype.Text        `db:"logo_url" json:"logo_url"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility BrandVisibility    `db:"visibility" json:"visibility"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.LogoUrl,
		arg.OwnerID,
		arg.Visibility,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, status, logo_url, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM brands
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBrandByID(ctx context.Context, id pgtype.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, status, logo_url, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM brands
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListBrandsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.LogoUrl,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBrand = `-- name: SoftDeleteBrand :exec
UPDATE brands SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteBrandParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteBrand(ctx context.Context, arg SoftDeleteBrandParams) error {
	_, err := q.db.Exec(ctx, softDeleteBrand, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands SET
  name = $2,
  status = $3,
  logo_url = $4,
  owner_id = $5,
  visibility = $6,
  updated_at = $7,
  updated_by = $8,
  deleted_at = $9,
  deleted_by = $10
WHERE id = $1
RETURNING id, name, status, logo_url, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateBrandParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     BrandStatus        `db:"status" json:"status"`
	LogoUrl    pgtype.Text        `db:"logo_url" json:"logo_url"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility BrandVisibility    `db:"visibility" json:"visibility"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.LogoUrl,
		arg.OwnerID,
		arg.Visibility,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
