// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
  id, status, name, parent_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, status, name, parent_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateCategoryParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Status    CategoryStatus     `db:"status" json:"status"`
	Name      string             `db:"name" json:"name"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parent_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, status, name, parent_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, status, name, parent_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM categories
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListCategoriesParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteCategoryParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
  status = $2,
  name = $3,
  parent_id = $4,
  updated_at = $5,
  updated_by = $6,
  deleted_at = $7,
  deleted_by = $8
WHERE id = $1
RETURNING id, status, name, parent_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateCategoryParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Status    CategoryStatus     `db:"status" json:"status"`
	Name      string             `db:"name" json:"name"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parent_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.ParentID,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
