// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_tags.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategoryTag = `-- name: CreateCategoryTag :one
INSERT INTO category_tags (category_id, tag_id, created_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING category_id, tag_id, created_at, created_by
`

type CreateCategoryTagParams struct {
	CategoryID pgtype.UUID        `db:"category_id" json:"category_id"`
	TagID      pgtype.UUID        `db:"tag_id" json:"tag_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCategoryTag(ctx context.Context, arg CreateCategoryTagParams) (CategoryTag, error) {
	row := q.db.QueryRow(ctx, createCategoryTag,
		arg.CategoryID,
		arg.TagID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i CategoryTag
	err := row.Scan(
		&i.CategoryID,
		&i.TagID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const removeCategoryTag = `-- name: RemoveCategoryTag :exec
DELETE FROM category_tags
WHERE category_id = $1 AND tag_id = $2
`

type RemoveCategoryTagParams struct {
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
	TagID      pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveCategoryTag(ctx context.Context, arg RemoveCategoryTagParams) error {
	_, err := q.db.Exec(ctx, removeCategoryTag, arg.CategoryID, arg.TagID)
	return err
}
