// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BrandStatus string

const (
	BrandStatusInactive BrandStatus = "inactive"
	BrandStatusActive   BrandStatus = "active"
	BrandStatusArchived BrandStatus = "archived"
)

func (e *BrandStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BrandStatus(s)
	case string:
		*e = BrandStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BrandStatus: %T", src)
	}
	return nil
}

type NullBrandStatus struct {
	BrandStatus BrandStatus `json:"brand_status"`
	Valid       bool        `json:"valid"` // Valid is true if BrandStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBrandStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BrandStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BrandStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBrandStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BrandStatus), nil
}

type BrandVisibility string

const (
	BrandVisibilityOfficial  BrandVisibility = "official"
	BrandVisibilityCommunity BrandVisibility = "community"
	BrandVisibilityPrivate   BrandVisibility = "private"
)

func (e *BrandVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BrandVisibility(s)
	case string:
		*e = BrandVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for BrandVisibility: %T", src)
	}
	return nil
}

type NullBrandVisibility struct {
	BrandVisibility BrandVisibility `json:"brand_visibility"`
	Valid           bool            `json:"valid"` // Valid is true if BrandVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBrandVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.BrandVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BrandVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBrandVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BrandVisibility), nil
}

type CategoryStatus string

const (
	CategoryStatusInactive CategoryStatus = "inactive"
	CategoryStatusActive   CategoryStatus = "active"
	CategoryStatusArchived CategoryStatus = "archived"
)

func (e *CategoryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryStatus(s)
	case string:
		*e = CategoryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryStatus: %T", src)
	}
	return nil
}

type NullCategoryStatus struct {
	CategoryStatus CategoryStatus `json:"category_status"`
	Valid          bool           `json:"valid"` // Valid is true if CategoryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryStatus), nil
}

type OutboxArchiveStatus string

const (
	OutboxArchiveStatusSuccess OutboxArchiveStatus = "success"
	OutboxArchiveStatusFailed  OutboxArchiveStatus = "failed"
)

func (e *OutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxArchiveStatus(s)
	case string:
		*e = OutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullOutboxArchiveStatus struct {
	OutboxArchiveStatus OutboxArchiveStatus `json:"outbox_archive_status"`
	Valid               bool                `json:"valid"` // Valid is true if OutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxArchiveStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type ProductNetUnit string

const (
	ProductNetUnitG  ProductNetUnit = "g"
	ProductNetUnitKg ProductNetUnit = "kg"
	ProductNetUnitMl ProductNetUnit = "ml"
	ProductNetUnitL  ProductNetUnit = "l"
)

func (e *ProductNetUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductNetUnit(s)
	case string:
		*e = ProductNetUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductNetUnit: %T", src)
	}
	return nil
}

type NullProductNetUnit struct {
	ProductNetUnit ProductNetUnit `json:"product_net_unit"`
	Valid          bool           `json:"valid"` // Valid is true if ProductNetUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductNetUnit) Scan(value interface{}) error {
	if value == nil {
		ns.ProductNetUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductNetUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductNetUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductNetUnit), nil
}

type ProductStatus string

const (
	ProductStatusInactive ProductStatus = "inactive"
	ProductStatusActive   ProductStatus = "active"
	ProductStatusArchived ProductStatus = "archived"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type ProductVisibility string

const (
	ProductVisibilityOfficial  ProductVisibility = "official"
	ProductVisibilityCommunity ProductVisibility = "community"
	ProductVisibilityPrivate   ProductVisibility = "private"
)

func (e *ProductVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductVisibility(s)
	case string:
		*e = ProductVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductVisibility: %T", src)
	}
	return nil
}

type NullProductVisibility struct {
	ProductVisibility ProductVisibility `json:"product_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ProductVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ProductVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductVisibility), nil
}

type ProviderRawDataStatus string

const (
	ProviderRawDataStatusPending   ProviderRawDataStatus = "pending"
	ProviderRawDataStatusProcessed ProviderRawDataStatus = "processed"
	ProviderRawDataStatusFailed    ProviderRawDataStatus = "failed"
)

func (e *ProviderRawDataStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderRawDataStatus(s)
	case string:
		*e = ProviderRawDataStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderRawDataStatus: %T", src)
	}
	return nil
}

type NullProviderRawDataStatus struct {
	ProviderRawDataStatus ProviderRawDataStatus `json:"provider_raw_data_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if ProviderRawDataStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderRawDataStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderRawDataStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderRawDataStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderRawDataStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderRawDataStatus), nil
}

type ProviderStatus string

const (
	ProviderStatusInactive ProviderStatus = "inactive"
	ProviderStatusActive   ProviderStatus = "active"
	ProviderStatusArchived ProviderStatus = "archived"
)

func (e *ProviderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderStatus(s)
	case string:
		*e = ProviderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderStatus: %T", src)
	}
	return nil
}

type NullProviderStatus struct {
	ProviderStatus ProviderStatus `json:"provider_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProviderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderStatus), nil
}

type Brand struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     BrandStatus        `db:"status" json:"status"`
	LogoUrl    pgtype.Text        `db:"logo_url" json:"logo_url"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility BrandVisibility    `db:"visibility" json:"visibility"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type BrandTag struct {
	BrandID   pgtype.UUID        `db:"brand_id" json:"brand_id"`
	TagID     pgtype.UUID        `db:"tag_id" json:"tag_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

type Category struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Status    CategoryStatus     `db:"status" json:"status"`
	Name      string             `db:"name" json:"name"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parent_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type CategoryTag struct {
	CategoryID pgtype.UUID        `db:"category_id" json:"category_id"`
	TagID      pgtype.UUID        `db:"tag_id" json:"tag_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type IdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxArchive struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID         `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID         `db:"trace_id" json:"trace_id"`
	Event          string              `db:"event" json:"event"`
	Payload        []byte              `db:"payload" json:"payload"`
	Status         OutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32               `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz  `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz  `db:"archived_at" json:"archived_at"`
}

type OutboxEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TraceID    pgtype.UUID        `db:"trace_id" json:"trace_id"`
	Event      string             `db:"event" json:"event"`
	Payload    []byte             `db:"payload" json:"payload"`
	Status     OutboxEventStatus  `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type Product struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Status     ProductStatus      `db:"status" json:"status"`
	Name       string             `db:"name" json:"name"`
	Barcode    pgtype.Text        `db:"barcode" json:"barcode"`
	NetValue   pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit    ProductNetUnit     `db:"net_unit" json:"net_unit"`
	ImageUrl   pgtype.Text        `db:"image_url" json:"image_url"`
	Nutriscore pgtype.Text        `db:"nutriscore" json:"nutriscore"`
	NovaGroup  pgtype.Int4        `db:"nova_group" json:"nova_group"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility ProductVisibility  `db:"visibility" json:"visibility"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type ProductBrand struct {
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	BrandID   pgtype.UUID        `db:"brand_id" json:"brand_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

type ProductCategory struct {
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	CategoryID pgtype.UUID        `db:"category_id" json:"category_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type ProductProvider struct {
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type Provider struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     ProviderStatus     `db:"status" json:"status"`
	WebsiteUrl pgtype.Text        `db:"website_url" json:"website_url"`
	LogoUrl    pgtype.Text        `db:"logo_url" json:"logo_url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type ProviderRawDatum struct {
	ID          pgtype.UUID           `db:"id" json:"id"`
	Barcode     pgtype.Text           `db:"barcode" json:"barcode"`
	Status      ProviderRawDataStatus `db:"status" json:"status"`
	ProviderID  pgtype.UUID           `db:"provider_id" json:"provider_id"`
	RawData     []byte                `db:"raw_data" json:"raw_data"`
	FetchedAt   pgtype.Timestamptz    `db:"fetched_at" json:"fetched_at"`
	ProcessedAt pgtype.Timestamptz    `db:"processed_at" json:"processed_at"`
}

type Tag struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}
