// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_archive.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxArchive = `-- name: CreateOutboxArchive :one
INSERT INTO catalog_write.outbox_archive (id, outbox_event_id, trace_id, event, payload, status, retry_count, event_created_at, archived_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, outbox_event_id, trace_id, event, payload, status, retry_count, event_created_at, archived_at
`

type CreateOutboxArchiveParams struct {
	ID             pgtype.UUID                     `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID                     `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID                     `db:"trace_id" json:"trace_id"`
	Event          string                          `db:"event" json:"event"`
	Payload        []byte                          `db:"payload" json:"payload"`
	Status         CatalogWriteOutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32                           `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz              `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz              `db:"archived_at" json:"archived_at"`
}

func (q *Queries) CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (CatalogWriteOutboxArchive, error) {
	row := q.db.QueryRow(ctx, createOutboxArchive,
		arg.ID,
		arg.OutboxEventID,
		arg.TraceID,
		arg.Event,
		arg.Payload,
		arg.Status,
		arg.RetryCount,
		arg.EventCreatedAt,
		arg.ArchivedAt,
	)
	var i CatalogWriteOutboxArchive
	err := row.Scan(
		&i.ID,
		&i.OutboxEventID,
		&i.TraceID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.EventCreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
