// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessedMessage = `-- name: CreateProcessedMessage :one
INSERT INTO catalog_write.processed_messages (message_id, processed_at)
VALUES ($1, $2)
RETURNING message_id, processed_at
`

type CreateProcessedMessageParams struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

func (q *Queries) CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (CatalogWriteProcessedMessage, error) {
	row := q.db.QueryRow(ctx, createProcessedMessage, arg.MessageID, arg.ProcessedAt)
	var i CatalogWriteProcessedMessage
	err := row.Scan(&i.MessageID, &i.ProcessedAt)
	return i, err
}

const getProcessedMessageByID = `-- name: GetProcessedMessageByID :one
SELECT message_id, processed_at FROM catalog_write.processed_messages
WHERE message_id = $1
`

func (q *Queries) GetProcessedMessageByID(ctx context.Context, messageID string) (CatalogWriteProcessedMessage, error) {
	row := q.db.QueryRow(ctx, getProcessedMessageByID, messageID)
	var i CatalogWriteProcessedMessage
	err := row.Scan(&i.MessageID, &i.ProcessedAt)
	return i, err
}
