// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  id, status, name, barcode, net_value, net_unit, image_url, nutriscore, nova_group, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, status, name, barcode, net_value, net_unit, image_url, nutriscore, nova_group, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateProductParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Status     ProductStatus      `db:"status" json:"status"`
	Name       string             `db:"name" json:"name"`
	Barcode    pgtype.Text        `db:"barcode" json:"barcode"`
	NetValue   pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit    ProductNetUnit     `db:"net_unit" json:"net_unit"`
	ImageUrl   pgtype.Text        `db:"image_url" json:"image_url"`
	Nutriscore pgtype.Text        `db:"nutriscore" json:"nutriscore"`
	NovaGroup  pgtype.Int4        `db:"nova_group" json:"nova_group"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility ProductVisibility  `db:"visibility" json:"visibility"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.Barcode,
		arg.NetValue,
		arg.NetUnit,
		arg.ImageUrl,
		arg.Nutriscore,
		arg.NovaGroup,
		arg.OwnerID,
		arg.Visibility,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Barcode,
		&i.NetValue,
		&i.NetUnit,
		&i.ImageUrl,
		&i.Nutriscore,
		&i.NovaGroup,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT id, status, name, barcode, net_value, net_unit, image_url, nutriscore, nova_group, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE barcode = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByBarcode(ctx context.Context, barcode pgtype.Text) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, barcode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Barcode,
		&i.NetValue,
		&i.NetUnit,
		&i.ImageUrl,
		&i.Nutriscore,
		&i.NovaGroup,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, status, name, barcode, net_value, net_unit, image_url, nutriscore, nova_group, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Barcode,
		&i.NetValue,
		&i.NetUnit,
		&i.ImageUrl,
		&i.Nutriscore,
		&i.NovaGroup,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, status, name, barcode, net_value, net_unit, image_url, nutriscore, nova_group, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListProductsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Barcode,
			&i.NetValue,
			&i.NetUnit,
			&i.ImageUrl,
			&i.Nutriscore,
			&i.NovaGroup,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteProductParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  status = $2,
  name = $3,
  barcode = $4,
  net_value = $5,
  net_unit = $6,
  image_url = $7,
  nutriscore = $8,
  nova_group = $9,
  owner_id = $10,
  visibility = $11,
  updated_at = $12,
  updated_by = $13,
  deleted_at = $14,
  deleted_by = $15
WHERE id = $1
RETURNING id, status, name, barcode, net_value, net_unit, image_url, nutriscore, nova_group, owner_id, visibility, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateProductParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Status     ProductStatus      `db:"status" json:"status"`
	Name       string             `db:"name" json:"name"`
	Barcode    pgtype.Text        `db:"barcode" json:"barcode"`
	NetValue   pgtype.Numeric     `db:"net_value" json:"net_value"`
	NetUnit    ProductNetUnit     `db:"net_unit" json:"net_unit"`
	ImageUrl   pgtype.Text        `db:"image_url" json:"image_url"`
	Nutriscore pgtype.Text        `db:"nutriscore" json:"nutriscore"`
	NovaGroup  pgtype.Int4        `db:"nova_group" json:"nova_group"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility ProductVisibility  `db:"visibility" json:"visibility"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.Barcode,
		arg.NetValue,
		arg.NetUnit,
		arg.ImageUrl,
		arg.Nutriscore,
		arg.NovaGroup,
		arg.OwnerID,
		arg.Visibility,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Barcode,
		&i.NetValue,
		&i.NetUnit,
		&i.ImageUrl,
		&i.Nutriscore,
		&i.NovaGroup,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
