// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_brands.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductBrand = `-- name: CreateProductBrand :one
INSERT INTO product_brands (product_id, brand_id, created_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING product_id, brand_id, created_at, created_by
`

type CreateProductBrandParams struct {
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	BrandID   pgtype.UUID        `db:"brand_id" json:"brand_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateProductBrand(ctx context.Context, arg CreateProductBrandParams) (ProductBrand, error) {
	row := q.db.QueryRow(ctx, createProductBrand,
		arg.ProductID,
		arg.BrandID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i ProductBrand
	err := row.Scan(
		&i.ProductID,
		&i.BrandID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const removeProductBrand = `-- name: RemoveProductBrand :exec
DELETE FROM product_brands
WHERE product_id = $1 AND brand_id = $2
`

type RemoveProductBrandParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	BrandID   pgtype.UUID `db:"brand_id" json:"brand_id"`
}

func (q *Queries) RemoveProductBrand(ctx context.Context, arg RemoveProductBrandParams) error {
	_, err := q.db.Exec(ctx, removeProductBrand, arg.ProductID, arg.BrandID)
	return err
}
