// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
  id, name, status, website_url, logo_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, status, website_url, logo_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateProviderParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     ProviderStatus     `db:"status" json:"status"`
	WebsiteUrl pgtype.Text        `db:"website_url" json:"website_url"`
	LogoUrl    pgtype.Text        `db:"logo_url" json:"logo_url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.WebsiteUrl,
		arg.LogoUrl,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.WebsiteUrl,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, status, website_url, logo_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM providers
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.WebsiteUrl,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, status, website_url, logo_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM providers
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListProvidersParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.WebsiteUrl,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProvider = `-- name: SoftDeleteProvider :exec
UPDATE providers SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteProviderParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteProvider(ctx context.Context, arg SoftDeleteProviderParams) error {
	_, err := q.db.Exec(ctx, softDeleteProvider, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET
  name = $2,
  status = $3,
  website_url = $4,
  logo_url = $5,
  updated_at = $6,
  updated_by = $7,
  deleted_at = $8,
  deleted_by = $9
WHERE id = $1
RETURNING id, name, status, website_url, logo_url, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateProviderParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     ProviderStatus     `db:"status" json:"status"`
	WebsiteUrl pgtype.Text        `db:"website_url" json:"website_url"`
	LogoUrl    pgtype.Text        `db:"logo_url" json:"logo_url"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.WebsiteUrl,
		arg.LogoUrl,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.WebsiteUrl,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
