// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_raw_data.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderRawData = `-- name: CreateProviderRawData :one
INSERT INTO provider_raw_data (
  id, barcode, status, provider_id, raw_data, fetched_at, processed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, barcode, status, provider_id, raw_data, fetched_at, processed_at
`

type CreateProviderRawDataParams struct {
	ID          pgtype.UUID           `db:"id" json:"id"`
	Barcode     pgtype.Text           `db:"barcode" json:"barcode"`
	Status      ProviderRawDataStatus `db:"status" json:"status"`
	ProviderID  pgtype.UUID           `db:"provider_id" json:"provider_id"`
	RawData     []byte                `db:"raw_data" json:"raw_data"`
	FetchedAt   pgtype.Timestamptz    `db:"fetched_at" json:"fetched_at"`
	ProcessedAt pgtype.Timestamptz    `db:"processed_at" json:"processed_at"`
}

func (q *Queries) CreateProviderRawData(ctx context.Context, arg CreateProviderRawDataParams) (ProviderRawDatum, error) {
	row := q.db.QueryRow(ctx, createProviderRawData,
		arg.ID,
		arg.Barcode,
		arg.Status,
		arg.ProviderID,
		arg.RawData,
		arg.FetchedAt,
		arg.ProcessedAt,
	)
	var i ProviderRawDatum
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Status,
		&i.ProviderID,
		&i.RawData,
		&i.FetchedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getProviderRawDataByID = `-- name: GetProviderRawDataByID :one
SELECT id, barcode, status, provider_id, raw_data, fetched_at, processed_at FROM provider_raw_data
WHERE id = $1
`

func (q *Queries) GetProviderRawDataByID(ctx context.Context, id pgtype.UUID) (ProviderRawDatum, error) {
	row := q.db.QueryRow(ctx, getProviderRawDataByID, id)
	var i ProviderRawDatum
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Status,
		&i.ProviderID,
		&i.RawData,
		&i.FetchedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const updateProviderRawDataStatus = `-- name: UpdateProviderRawDataStatus :one
UPDATE provider_raw_data SET
  status = $2,
  processed_at = $3
WHERE id = $1
RETURNING id, barcode, status, provider_id, raw_data, fetched_at, processed_at
`

type UpdateProviderRawDataStatusParams struct {
	ID          pgtype.UUID           `db:"id" json:"id"`
	Status      ProviderRawDataStatus `db:"status" json:"status"`
	ProcessedAt pgtype.Timestamptz    `db:"processed_at" json:"processed_at"`
}

func (q *Queries) UpdateProviderRawDataStatus(ctx context.Context, arg UpdateProviderRawDataStatusParams) (ProviderRawDatum, error) {
	row := q.db.QueryRow(ctx, updateProviderRawDataStatus, arg.ID, arg.Status, arg.ProcessedAt)
	var i ProviderRawDatum
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Status,
		&i.ProviderID,
		&i.RawData,
		&i.FetchedAt,
		&i.ProcessedAt,
	)
	return i, err
}
