// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
  id, name, provider_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, provider_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateTagParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.Name,
		arg.ProviderID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, provider_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tags
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, provider_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tags
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, provider_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tags
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListTagsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteTagParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) error {
	_, err := q.db.Exec(ctx, softDeleteTag, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET
  name = $2,
  provider_id = $3,
  updated_at = $4,
  updated_by = $5,
  deleted_at = $6,
  deleted_by = $7
WHERE id = $1
RETURNING id, name, provider_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateTagParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	ProviderID pgtype.UUID        `db:"provider_id" json:"provider_id"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.ProviderID,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
