// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewStock struct {
	StockID           pgtype.UUID        `db:"stock_id" json:"stock_id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName       string             `db:"product_name" json:"product_name"`
	ProductBrands     pgtype.Text        `db:"product_brands" json:"product_brands"`
	ProductCategories pgtype.Text        `db:"product_categories" json:"product_categories"`
	AreaID            pgtype.UUID        `db:"area_id" json:"area_id"`
	AreaName          pgtype.Text        `db:"area_name" json:"area_name"`
	QuantityDisplay   string             `db:"quantity_display" json:"quantity_display"`
	NetUnit           string             `db:"net_unit" json:"net_unit"`
	TotalValue        pgtype.Numeric     `db:"total_value" json:"total_value"`
	Status            string             `db:"status" json:"status"`
	OwnerPartyID      pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ViewStockTransaction struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	ProductBrands   pgtype.Text        `db:"product_brands" json:"product_brands"`
	ProductImageUrl pgtype.Text        `db:"product_image_url" json:"product_image_url"`
	Action          string             `db:"action" json:"action"`
	ActorID         pgtype.UUID        `db:"actor_id" json:"actor_id"`
	ActorName       pgtype.Text        `db:"actor_name" json:"actor_name"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetUnit         string             `db:"net_unit" json:"net_unit"`
	DeltaValue      pgtype.Numeric     `db:"delta_value" json:"delta_value"`
	OwnerPartyID    pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
