// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetViewStockByID(ctx context.Context, stockID pgtype.UUID) (ViewStock, error)
	GetViewStockTransactionByID(ctx context.Context, id pgtype.UUID) (ViewStockTransaction, error)
	ListViewStock(ctx context.Context, arg ListViewStockParams) ([]ViewStock, error)
	ListViewStockTransactions(ctx context.Context, arg ListViewStockTransactionsParams) ([]ViewStockTransaction, error)
}

var _ Querier = (*Queries)(nil)
