// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  id, name, list_id, product_ids, is_ticked, quantity, reason, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, list_id, product_ids, is_ticked, quantity, reason, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateItemParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	ListID     pgtype.UUID        `db:"list_id" json:"list_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	IsTicked   bool               `db:"is_ticked" json:"is_ticked"`
	Quantity   int32              `db:"quantity" json:"quantity"`
	Reason     pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.ListID,
		arg.ProductIds,
		arg.IsTicked,
		arg.Quantity,
		arg.Reason,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListID,
		&i.ProductIds,
		&i.IsTicked,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, list_id, product_ids, is_ticked, quantity, reason, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM items
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListID,
		&i.ProductIds,
		&i.IsTicked,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteItem = `-- name: SoftDeleteItem :exec
UPDATE items SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteItemParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteItem, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET
  name = $2,
  list_id = $3,
  product_ids = $4,
  is_ticked = $5,
  quantity = $6,
  reason = $7,
  updated_at = $8,
  updated_by = $9,
  deleted_at = $10,
  deleted_by = $11
WHERE id = $1
RETURNING id, name, list_id, product_ids, is_ticked, quantity, reason, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateItemParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	ListID     pgtype.UUID        `db:"list_id" json:"list_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	IsTicked   bool               `db:"is_ticked" json:"is_ticked"`
	Quantity   int32              `db:"quantity" json:"quantity"`
	Reason     pgtype.Text        `db:"reason" json:"reason"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.ListID,
		arg.ProductIds,
		arg.IsTicked,
		arg.Quantity,
		arg.Reason,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListID,
		&i.ProductIds,
		&i.IsTicked,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
