// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ListsStatus string

const (
	ListsStatusDraft     ListsStatus = "draft"
	ListsStatusReady     ListsStatus = "ready"
	ListsStatusActive    ListsStatus = "active"
	ListsStatusCompleted ListsStatus = "completed"
	ListsStatusDiscarded ListsStatus = "discarded"
)

func (e *ListsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListsStatus(s)
	case string:
		*e = ListsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListsStatus: %T", src)
	}
	return nil
}

type NullListsStatus struct {
	ListsStatus ListsStatus `json:"lists_status"`
	Valid       bool        `json:"valid"` // Valid is true if ListsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListsStatus), nil
}

type OutboxArchiveStatus string

const (
	OutboxArchiveStatusSuccess OutboxArchiveStatus = "success"
	OutboxArchiveStatusFailed  OutboxArchiveStatus = "failed"
)

func (e *OutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxArchiveStatus(s)
	case string:
		*e = OutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullOutboxArchiveStatus struct {
	OutboxArchiveStatus OutboxArchiveStatus `json:"outbox_archive_status"`
	Valid               bool                `json:"valid"` // Valid is true if OutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxArchiveStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type ShopsStatus string

const (
	ShopsStatusInactive ShopsStatus = "inactive"
	ShopsStatusActive   ShopsStatus = "active"
)

func (e *ShopsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShopsStatus(s)
	case string:
		*e = ShopsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShopsStatus: %T", src)
	}
	return nil
}

type NullShopsStatus struct {
	ShopsStatus ShopsStatus `json:"shops_status"`
	Valid       bool        `json:"valid"` // Valid is true if ShopsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShopsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShopsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShopsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShopsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShopsStatus), nil
}

type IdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Item struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	ListID     pgtype.UUID        `db:"list_id" json:"list_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	IsTicked   bool               `db:"is_ticked" json:"is_ticked"`
	Quantity   int32              `db:"quantity" json:"quantity"`
	Reason     pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy  pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type List struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         pgtype.Text        `db:"name" json:"name"`
	Status       ListsStatus        `db:"status" json:"status"`
	ShoppingDate pgtype.Date        `db:"shopping_date" json:"shopping_date"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	ShopID       pgtype.UUID        `db:"shop_id" json:"shop_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    string             `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

type OutboxArchive struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID         `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID         `db:"trace_id" json:"trace_id"`
	Event          string              `db:"event" json:"event"`
	Payload        []byte              `db:"payload" json:"payload"`
	Status         OutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32               `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz  `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz  `db:"archived_at" json:"archived_at"`
}

type OutboxEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TraceID    pgtype.UUID        `db:"trace_id" json:"trace_id"`
	Event      string             `db:"event" json:"event"`
	Payload    []byte             `db:"payload" json:"payload"`
	Status     OutboxEventStatus  `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type Shop struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Status            ShopsStatus        `db:"status" json:"status"`
	Provider          string             `db:"provider" json:"provider"`
	PlaceID           pgtype.Text        `db:"place_id" json:"place_id"`
	PlaceUrl          pgtype.Text        `db:"place_url" json:"place_url"`
	Latitude          pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric     `db:"longitude" json:"longitude"`
	FormattedAddress  string             `db:"formatted_address" json:"formatted_address"`
	AddressComponents []byte             `db:"address_components" json:"address_components"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         string             `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy         pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy         pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}
