// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (OutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (ProcessedMessage, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (IdempotencyKey, error)
	GetItemByID(ctx context.Context, id pgtype.UUID) (Item, error)
	GetListByID(ctx context.Context, id pgtype.UUID) (List, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]OutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (ProcessedMessage, error)
	GetShopByID(ctx context.Context, id pgtype.UUID) (Shop, error)
	SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) error
	SoftDeleteList(ctx context.Context, arg SoftDeleteListParams) error
	SoftDeleteShop(ctx context.Context, arg SoftDeleteShopParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (OutboxEvent, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
}

var _ Querier = (*Queries)(nil)
