// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
  id, name, recipe_id, product_ids, created_at, created_by, updated_at, updated_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, recipe_id, product_ids, created_at, created_by, updated_at, updated_by
`

type CreateIngredientParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	RecipeID   pgtype.UUID        `db:"recipe_id" json:"recipe_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.ID,
		arg.Name,
		arg.RecipeID,
		arg.ProductIds,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RecipeID,
		&i.ProductIds,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients
WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIngredient, id)
	return err
}

const getIngredientByID = `-- name: GetIngredientByID :one
SELECT id, name, recipe_id, product_ids, created_at, created_by, updated_at, updated_by FROM ingredients
WHERE id = $1
`

func (q *Queries) GetIngredientByID(ctx context.Context, id pgtype.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RecipeID,
		&i.ProductIds,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients SET
  name = $2,
  recipe_id = $3,
  product_ids = $4,
  updated_at = $5,
  updated_by = $6
WHERE id = $1
RETURNING id, name, recipe_id, product_ids, created_at, created_by, updated_at, updated_by
`

type UpdateIngredientParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	RecipeID   pgtype.UUID        `db:"recipe_id" json:"recipe_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.Name,
		arg.RecipeID,
		arg.ProductIds,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RecipeID,
		&i.ProductIds,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
