// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxArchiveStatus string

const (
	OutboxArchiveStatusSuccess OutboxArchiveStatus = "success"
	OutboxArchiveStatusFailed  OutboxArchiveStatus = "failed"
)

func (e *OutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxArchiveStatus(s)
	case string:
		*e = OutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullOutboxArchiveStatus struct {
	OutboxArchiveStatus OutboxArchiveStatus `json:"outbox_archive_status"`
	Valid               bool                `json:"valid"` // Valid is true if OutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxArchiveStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type RecipesStatus string

const (
	RecipesStatusDraft    RecipesStatus = "draft"
	RecipesStatusInactive RecipesStatus = "inactive"
	RecipesStatusActive   RecipesStatus = "active"
)

func (e *RecipesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecipesStatus(s)
	case string:
		*e = RecipesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecipesStatus: %T", src)
	}
	return nil
}

type NullRecipesStatus struct {
	RecipesStatus RecipesStatus `json:"recipes_status"`
	Valid         bool          `json:"valid"` // Valid is true if RecipesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecipesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecipesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecipesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecipesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecipesStatus), nil
}

type RecipesVisibility string

const (
	RecipesVisibilityOfficial  RecipesVisibility = "official"
	RecipesVisibilityCommunity RecipesVisibility = "community"
	RecipesVisibilityPrivate   RecipesVisibility = "private"
)

func (e *RecipesVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecipesVisibility(s)
	case string:
		*e = RecipesVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for RecipesVisibility: %T", src)
	}
	return nil
}

type NullRecipesVisibility struct {
	RecipesVisibility RecipesVisibility `json:"recipes_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if RecipesVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecipesVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.RecipesVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecipesVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecipesVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecipesVisibility), nil
}

type IdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Ingredient struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	RecipeID   pgtype.UUID        `db:"recipe_id" json:"recipe_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
}

type OutboxArchive struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID         `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID         `db:"trace_id" json:"trace_id"`
	Event          string              `db:"event" json:"event"`
	Payload        []byte              `db:"payload" json:"payload"`
	Status         OutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32               `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz  `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz  `db:"archived_at" json:"archived_at"`
}

type OutboxEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TraceID    pgtype.UUID        `db:"trace_id" json:"trace_id"`
	Event      string             `db:"event" json:"event"`
	Payload    []byte             `db:"payload" json:"payload"`
	Status     OutboxEventStatus  `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type Recipe struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Status       RecipesStatus      `db:"status" json:"status"`
	Visibility   RecipesVisibility  `db:"visibility" json:"visibility"`
	Instructions []byte             `db:"instructions" json:"instructions"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    string             `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}
