// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (OutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (ProcessedMessage, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeleteIngredient(ctx context.Context, id pgtype.UUID) error
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (IdempotencyKey, error)
	GetIngredientByID(ctx context.Context, id pgtype.UUID) (Ingredient, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]OutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (ProcessedMessage, error)
	GetRecipeByID(ctx context.Context, id pgtype.UUID) (Recipe, error)
	SoftDeleteRecipe(ctx context.Context, arg SoftDeleteRecipeParams) error
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (OutboxEvent, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
