// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package dbwrite

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
  id, name, status, visibility, instructions, owner_id, owner_party_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, status, visibility, instructions, owner_id, owner_party_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateRecipeParams struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Status       RecipesStatus      `db:"status" json:"status"`
	Visibility   RecipesVisibility  `db:"visibility" json:"visibility"`
	Instructions []byte             `db:"instructions" json:"instructions"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    string             `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Visibility,
		arg.Instructions,
		arg.OwnerID,
		arg.OwnerPartyID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Visibility,
		&i.Instructions,
		&i.OwnerID,
		&i.OwnerPartyID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, name, status, visibility, instructions, owner_id, owner_party_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM recipes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRecipeByID(ctx context.Context, id pgtype.UUID) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Visibility,
		&i.Instructions,
		&i.OwnerID,
		&i.OwnerPartyID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteRecipe = `-- name: SoftDeleteRecipe :exec
UPDATE recipes SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteRecipeParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteRecipe(ctx context.Context, arg SoftDeleteRecipeParams) error {
	_, err := q.db.Exec(ctx, softDeleteRecipe, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes SET
  name = $2,
  status = $3,
  visibility = $4,
  instructions = $5,
  owner_id = $6,
  owner_party_id = $7,
  updated_at = $8,
  updated_by = $9,
  deleted_at = $10,
  deleted_by = $11
WHERE id = $1
RETURNING id, name, status, visibility, instructions, owner_id, owner_party_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateRecipeParams struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Status       RecipesStatus      `db:"status" json:"status"`
	Visibility   RecipesVisibility  `db:"visibility" json:"visibility"`
	Instructions []byte             `db:"instructions" json:"instructions"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text        `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Visibility,
		arg.Instructions,
		arg.OwnerID,
		arg.OwnerPartyID,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Visibility,
		&i.Instructions,
		&i.OwnerID,
		&i.OwnerPartyID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
