// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewInboxMessage struct {
	InboxMessageID pgtype.UUID        `db:"inbox_message_id" json:"inbox_message_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	Name           string             `db:"name" json:"name"`
	Status         string             `db:"status" json:"status"`
	Title          string             `db:"title" json:"title"`
	Content        string             `db:"content" json:"content"`
	LinkUrl        pgtype.Text        `db:"link_url" json:"link_url"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy      string             `db:"created_by" json:"created_by"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy      pgtype.Text        `db:"updated_by" json:"updated_by"`
}
