// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetViewInboxMessageByID(ctx context.Context, inboxMessageID pgtype.UUID) (ViewInboxMessage, error)
	ListViewInboxMessagesByUser(ctx context.Context, arg ListViewInboxMessagesByUserParams) ([]ViewInboxMessage, error)
}

var _ Querier = (*Queries)(nil)
