// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_inbox_messages.sql

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewInboxMessageByID = `-- name: GetViewInboxMessageByID :one
SELECT inbox_message_id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by FROM view_inbox_messages
WHERE inbox_message_id = $1
`

func (q *Queries) GetViewInboxMessageByID(ctx context.Context, inboxMessageID pgtype.UUID) (ViewInboxMessage, error) {
	row := q.db.QueryRow(ctx, getViewInboxMessageByID, inboxMessageID)
	var i ViewInboxMessage
	err := row.Scan(
		&i.InboxMessageID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.LinkUrl,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listViewInboxMessagesByUser = `-- name: ListViewInboxMessagesByUser :many
SELECT inbox_message_id, user_id, name, status, title, content, link_url, created_at, created_by, updated_at, updated_by FROM view_inbox_messages
WHERE ($2::timestamptz IS NULL OR (created_at, inbox_message_id) < ($2::timestamptz, $3::uuid))
  AND user_id = $1
ORDER BY created_at DESC, inbox_message_id DESC
LIMIT $4
`

type ListViewInboxMessagesByUserParams struct {
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewInboxMessagesByUser(ctx context.Context, arg ListViewInboxMessagesByUserParams) ([]ViewInboxMessage, error) {
	rows, err := q.db.Query(ctx, listViewInboxMessagesByUser,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewInboxMessage{}
	for rows.Next() {
		var i ViewInboxMessage
		if err := rows.Scan(
			&i.InboxMessageID,
			&i.UserID,
			&i.Name,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.LinkUrl,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
