// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: areas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArea = `-- name: CreateArea :one
INSERT INTO inventory_write.areas (
  id, name, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateAreaParams struct {
	ID        pgtype.UUID              `db:"id" json:"id"`
	Name      string                   `db:"name" json:"name"`
	Status    InventoryWriteAreaStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	CreatedBy string                   `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (InventoryWriteArea, error) {
	row := q.db.QueryRow(ctx, createArea,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i InventoryWriteArea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getAreaByID = `-- name: GetAreaByID :one
SELECT id, name, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM inventory_write.areas
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAreaByID(ctx context.Context, id pgtype.UUID) (InventoryWriteArea, error) {
	row := q.db.QueryRow(ctx, getAreaByID, id)
	var i InventoryWriteArea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteArea = `-- name: SoftDeleteArea :exec
UPDATE inventory_write.areas SET
  deleted_at = $2,
  deleted_by = $3
WHERE id = $1
`

type SoftDeleteAreaParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text        `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) SoftDeleteArea(ctx context.Context, arg SoftDeleteAreaParams) error {
	_, err := q.db.Exec(ctx, softDeleteArea, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateArea = `-- name: UpdateArea :one
UPDATE inventory_write.areas SET
  name = $2,
  status = $3,
  updated_at = $4,
  updated_by = $5,
  deleted_at = $6,
  deleted_by = $7
WHERE id = $1
RETURNING id, name, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateAreaParams struct {
	ID        pgtype.UUID              `db:"id" json:"id"`
	Name      string                   `db:"name" json:"name"`
	Status    InventoryWriteAreaStatus `db:"status" json:"status"`
	UpdatedAt pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

func (q *Queries) UpdateArea(ctx context.Context, arg UpdateAreaParams) (InventoryWriteArea, error) {
	row := q.db.QueryRow(ctx, updateArea,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	var i InventoryWriteArea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
