// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryWriteAreaStatus string

const (
	InventoryWriteAreaStatusActive   InventoryWriteAreaStatus = "active"
	InventoryWriteAreaStatusInactive InventoryWriteAreaStatus = "inactive"
)

func (e *InventoryWriteAreaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryWriteAreaStatus(s)
	case string:
		*e = InventoryWriteAreaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryWriteAreaStatus: %T", src)
	}
	return nil
}

type NullInventoryWriteAreaStatus struct {
	InventoryWriteAreaStatus InventoryWriteAreaStatus `json:"inventory_write_area_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if InventoryWriteAreaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryWriteAreaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryWriteAreaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryWriteAreaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryWriteAreaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryWriteAreaStatus), nil
}

type InventoryWriteOutboxArchiveStatus string

const (
	InventoryWriteOutboxArchiveStatusSuccess InventoryWriteOutboxArchiveStatus = "success"
	InventoryWriteOutboxArchiveStatusFailed  InventoryWriteOutboxArchiveStatus = "failed"
)

func (e *InventoryWriteOutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryWriteOutboxArchiveStatus(s)
	case string:
		*e = InventoryWriteOutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryWriteOutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullInventoryWriteOutboxArchiveStatus struct {
	InventoryWriteOutboxArchiveStatus InventoryWriteOutboxArchiveStatus `json:"inventory_write_outbox_archive_status"`
	Valid                             bool                              `json:"valid"` // Valid is true if InventoryWriteOutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryWriteOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryWriteOutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryWriteOutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryWriteOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryWriteOutboxArchiveStatus), nil
}

type InventoryWriteOutboxEventStatus string

const (
	InventoryWriteOutboxEventStatusPending    InventoryWriteOutboxEventStatus = "pending"
	InventoryWriteOutboxEventStatusProcessing InventoryWriteOutboxEventStatus = "processing"
	InventoryWriteOutboxEventStatusFailed     InventoryWriteOutboxEventStatus = "failed"
)

func (e *InventoryWriteOutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryWriteOutboxEventStatus(s)
	case string:
		*e = InventoryWriteOutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryWriteOutboxEventStatus: %T", src)
	}
	return nil
}

type NullInventoryWriteOutboxEventStatus struct {
	InventoryWriteOutboxEventStatus InventoryWriteOutboxEventStatus `json:"inventory_write_outbox_event_status"`
	Valid                           bool                            `json:"valid"` // Valid is true if InventoryWriteOutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryWriteOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryWriteOutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryWriteOutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryWriteOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryWriteOutboxEventStatus), nil
}

type InventoryWriteStockNetUnit string

const (
	InventoryWriteStockNetUnitG  InventoryWriteStockNetUnit = "g"
	InventoryWriteStockNetUnitKg InventoryWriteStockNetUnit = "kg"
	InventoryWriteStockNetUnitMl InventoryWriteStockNetUnit = "ml"
	InventoryWriteStockNetUnitL  InventoryWriteStockNetUnit = "l"
)

func (e *InventoryWriteStockNetUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryWriteStockNetUnit(s)
	case string:
		*e = InventoryWriteStockNetUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryWriteStockNetUnit: %T", src)
	}
	return nil
}

type NullInventoryWriteStockNetUnit struct {
	InventoryWriteStockNetUnit InventoryWriteStockNetUnit `json:"inventory_write_stock_net_unit"`
	Valid                      bool                       `json:"valid"` // Valid is true if InventoryWriteStockNetUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryWriteStockNetUnit) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryWriteStockNetUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryWriteStockNetUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryWriteStockNetUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryWriteStockNetUnit), nil
}

type InventoryWriteStockStatus string

const (
	InventoryWriteStockStatusAvailable InventoryWriteStockStatus = "available"
	InventoryWriteStockStatusReserved  InventoryWriteStockStatus = "reserved"
	InventoryWriteStockStatusOpened    InventoryWriteStockStatus = "opened"
	InventoryWriteStockStatusExpired   InventoryWriteStockStatus = "expired"
	InventoryWriteStockStatusConsumed  InventoryWriteStockStatus = "consumed"
	InventoryWriteStockStatusDiscarded InventoryWriteStockStatus = "discarded"
	InventoryWriteStockStatusLost      InventoryWriteStockStatus = "lost"
)

func (e *InventoryWriteStockStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryWriteStockStatus(s)
	case string:
		*e = InventoryWriteStockStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryWriteStockStatus: %T", src)
	}
	return nil
}

type NullInventoryWriteStockStatus struct {
	InventoryWriteStockStatus InventoryWriteStockStatus `json:"inventory_write_stock_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if InventoryWriteStockStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryWriteStockStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryWriteStockStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryWriteStockStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryWriteStockStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryWriteStockStatus), nil
}

type InventoryWriteStockTransactionsAction string

const (
	InventoryWriteStockTransactionsActionAdded     InventoryWriteStockTransactionsAction = "added"
	InventoryWriteStockTransactionsActionConsumed  InventoryWriteStockTransactionsAction = "consumed"
	InventoryWriteStockTransactionsActionOpened    InventoryWriteStockTransactionsAction = "opened"
	InventoryWriteStockTransactionsActionDiscarded InventoryWriteStockTransactionsAction = "discarded"
	InventoryWriteStockTransactionsActionExpired   InventoryWriteStockTransactionsAction = "expired"
	InventoryWriteStockTransactionsActionMoved     InventoryWriteStockTransactionsAction = "moved"
	InventoryWriteStockTransactionsActionCorrected InventoryWriteStockTransactionsAction = "corrected"
)

func (e *InventoryWriteStockTransactionsAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryWriteStockTransactionsAction(s)
	case string:
		*e = InventoryWriteStockTransactionsAction(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryWriteStockTransactionsAction: %T", src)
	}
	return nil
}

type NullInventoryWriteStockTransactionsAction struct {
	InventoryWriteStockTransactionsAction InventoryWriteStockTransactionsAction `json:"inventory_write_stock_transactions_action"`
	Valid                                 bool                                  `json:"valid"` // Valid is true if InventoryWriteStockTransactionsAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryWriteStockTransactionsAction) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryWriteStockTransactionsAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryWriteStockTransactionsAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryWriteStockTransactionsAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryWriteStockTransactionsAction), nil
}

type InventoryReadViewStock struct {
	StockID           pgtype.UUID        `db:"stock_id" json:"stock_id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName       string             `db:"product_name" json:"product_name"`
	ProductBrands     pgtype.Text        `db:"product_brands" json:"product_brands"`
	ProductCategories pgtype.Text        `db:"product_categories" json:"product_categories"`
	AreaID            pgtype.UUID        `db:"area_id" json:"area_id"`
	AreaName          pgtype.Text        `db:"area_name" json:"area_name"`
	QuantityDisplay   string             `db:"quantity_display" json:"quantity_display"`
	NetUnit           string             `db:"net_unit" json:"net_unit"`
	TotalValue        pgtype.Numeric     `db:"total_value" json:"total_value"`
	Status            string             `db:"status" json:"status"`
	OwnerPartyID      pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InventoryReadViewStockTransaction struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	ProductBrands   pgtype.Text        `db:"product_brands" json:"product_brands"`
	ProductImageUrl pgtype.Text        `db:"product_image_url" json:"product_image_url"`
	Action          string             `db:"action" json:"action"`
	ActorID         pgtype.UUID        `db:"actor_id" json:"actor_id"`
	ActorName       pgtype.Text        `db:"actor_name" json:"actor_name"`
	QuantityDisplay string             `db:"quantity_display" json:"quantity_display"`
	NetUnit         string             `db:"net_unit" json:"net_unit"`
	DeltaValue      pgtype.Numeric     `db:"delta_value" json:"delta_value"`
	OwnerPartyID    pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InventoryWriteArea struct {
	ID        pgtype.UUID              `db:"id" json:"id"`
	Name      string                   `db:"name" json:"name"`
	Status    InventoryWriteAreaStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	CreatedBy string                   `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Text              `db:"updated_by" json:"updated_by"`
	DeletedAt pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	DeletedBy pgtype.Text              `db:"deleted_by" json:"deleted_by"`
}

type InventoryWriteIdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InventoryWriteOutboxArchive struct {
	ID             pgtype.UUID                       `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID                       `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID                       `db:"trace_id" json:"trace_id"`
	Event          string                            `db:"event" json:"event"`
	Payload        []byte                            `db:"payload" json:"payload"`
	Status         InventoryWriteOutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32                             `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz                `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz                `db:"archived_at" json:"archived_at"`
}

type InventoryWriteOutboxEvent struct {
	ID         pgtype.UUID                     `db:"id" json:"id"`
	TraceID    pgtype.UUID                     `db:"trace_id" json:"trace_id"`
	Event      string                          `db:"event" json:"event"`
	Payload    []byte                          `db:"payload" json:"payload"`
	Status     InventoryWriteOutboxEventStatus `db:"status" json:"status"`
	RetryCount int32                           `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz              `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz              `db:"updated_at" json:"updated_at"`
}

type InventoryWriteProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type InventoryWriteStock struct {
	ID              pgtype.UUID                `db:"id" json:"id"`
	ProductID       pgtype.UUID                `db:"product_id" json:"product_id"`
	AreaID          pgtype.UUID                `db:"area_id" json:"area_id"`
	Status          InventoryWriteStockStatus  `db:"status" json:"status"`
	OwnerPartyID    pgtype.UUID                `db:"owner_party_id" json:"owner_party_id"`
	Quantity        int32                      `db:"quantity" json:"quantity"`
	QuantityDisplay string                     `db:"quantity_display" json:"quantity_display"`
	NetValue        pgtype.Numeric             `db:"net_value" json:"net_value"`
	NetUnit         InventoryWriteStockNetUnit `db:"net_unit" json:"net_unit"`
	RemainingValue  pgtype.Numeric             `db:"remaining_value" json:"remaining_value"`
	ExpiresAt       pgtype.Timestamptz         `db:"expires_at" json:"expires_at"`
	CreatedAt       pgtype.Timestamptz         `db:"created_at" json:"created_at"`
	CreatedBy       string                     `db:"created_by" json:"created_by"`
	UpdatedAt       pgtype.Timestamptz         `db:"updated_at" json:"updated_at"`
	UpdatedBy       pgtype.Text                `db:"updated_by" json:"updated_by"`
	DeletedAt       pgtype.Timestamptz         `db:"deleted_at" json:"deleted_at"`
	DeletedBy       pgtype.Text                `db:"deleted_by" json:"deleted_by"`
}

type InventoryWriteStockTransaction struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	StockID             pgtype.UUID        `db:"stock_id" json:"stock_id"`
	Action              string             `db:"action" json:"action"`
	DeltaQuantity       int32              `db:"delta_quantity" json:"delta_quantity"`
	DeltaRemainingValue pgtype.Numeric     `db:"delta_remaining_value" json:"delta_remaining_value"`
	Payload             []byte             `db:"payload" json:"payload"`
	OwnerPartyID        pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	ActorID             pgtype.UUID        `db:"actor_id" json:"actor_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy           string             `db:"created_by" json:"created_by"`
}
