// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateArea(ctx context.Context, arg CreateAreaParams) (InventoryWriteArea, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (InventoryWriteIdempotencyKey, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (InventoryWriteOutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (InventoryWriteOutboxEvent, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (InventoryWriteProcessedMessage, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (InventoryWriteStock, error)
	CreateStockTransaction(ctx context.Context, arg CreateStockTransactionParams) (InventoryWriteStockTransaction, error)
	GetAreaByID(ctx context.Context, id pgtype.UUID) (InventoryWriteArea, error)
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (InventoryWriteIdempotencyKey, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]InventoryWriteOutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (InventoryWriteProcessedMessage, error)
	GetStockByID(ctx context.Context, id pgtype.UUID) (InventoryWriteStock, error)
	GetStockTransactionByID(ctx context.Context, id pgtype.UUID) (InventoryWriteStockTransaction, error)
	GetViewStockByID(ctx context.Context, stockID pgtype.UUID) (InventoryReadViewStock, error)
	GetViewStockTransactionByID(ctx context.Context, id pgtype.UUID) (InventoryReadViewStockTransaction, error)
	ListViewStock(ctx context.Context, arg ListViewStockParams) ([]InventoryReadViewStock, error)
	ListViewStockTransactions(ctx context.Context, arg ListViewStockTransactionsParams) ([]InventoryReadViewStockTransaction, error)
	SoftDeleteArea(ctx context.Context, arg SoftDeleteAreaParams) error
	SoftDeleteStock(ctx context.Context, arg SoftDeleteStockParams) error
	UpdateArea(ctx context.Context, arg UpdateAreaParams) (InventoryWriteArea, error)
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (InventoryWriteOutboxEvent, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (InventoryWriteStock, error)
}

var _ Querier = (*Queries)(nil)
