// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_stock_transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewStockTransactionByID = `-- name: GetViewStockTransactionByID :one
SELECT id, product_id, product_name, product_brands, product_image_url, action, actor_id, actor_name, quantity_display, net_unit, delta_value, owner_party_id, created_at FROM inventory_read.view_stock_transactions
WHERE id = $1
`

func (q *Queries) GetViewStockTransactionByID(ctx context.Context, id pgtype.UUID) (InventoryReadViewStockTransaction, error) {
	row := q.db.QueryRow(ctx, getViewStockTransactionByID, id)
	var i InventoryReadViewStockTransaction
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductBrands,
		&i.ProductImageUrl,
		&i.Action,
		&i.ActorID,
		&i.ActorName,
		&i.QuantityDisplay,
		&i.NetUnit,
		&i.DeltaValue,
		&i.OwnerPartyID,
		&i.CreatedAt,
	)
	return i, err
}

const listViewStockTransactions = `-- name: ListViewStockTransactions :many
SELECT id, product_id, product_name, product_brands, product_image_url, action, actor_id, actor_name, quantity_display, net_unit, delta_value, owner_party_id, created_at FROM inventory_read.view_stock_transactions
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListViewStockTransactionsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewStockTransactions(ctx context.Context, arg ListViewStockTransactionsParams) ([]InventoryReadViewStockTransaction, error) {
	rows, err := q.db.Query(ctx, listViewStockTransactions, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReadViewStockTransaction{}
	for rows.Next() {
		var i InventoryReadViewStockTransaction
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.ProductBrands,
			&i.ProductImageUrl,
			&i.Action,
			&i.ActorID,
			&i.ActorName,
			&i.QuantityDisplay,
			&i.NetUnit,
			&i.DeltaValue,
			&i.OwnerPartyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
