// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_stock.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewStockByID = `-- name: GetViewStockByID :one
SELECT stock_id, product_id, product_name, product_brands, product_categories, area_id, area_name, quantity_display, net_unit, total_value, status, owner_party_id, created_at, updated_at FROM inventory_read.view_stock
WHERE stock_id = $1
`

func (q *Queries) GetViewStockByID(ctx context.Context, stockID pgtype.UUID) (InventoryReadViewStock, error) {
	row := q.db.QueryRow(ctx, getViewStockByID, stockID)
	var i InventoryReadViewStock
	err := row.Scan(
		&i.StockID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductBrands,
		&i.ProductCategories,
		&i.AreaID,
		&i.AreaName,
		&i.QuantityDisplay,
		&i.NetUnit,
		&i.TotalValue,
		&i.Status,
		&i.OwnerPartyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewStock = `-- name: ListViewStock :many
SELECT stock_id, product_id, product_name, product_brands, product_categories, area_id, area_name, quantity_display, net_unit, total_value, status, owner_party_id, created_at, updated_at FROM inventory_read.view_stock
WHERE ($1::timestamptz IS NULL OR (created_at, stock_id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, stock_id DESC
LIMIT $3
`

type ListViewStockParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewStock(ctx context.Context, arg ListViewStockParams) ([]InventoryReadViewStock, error) {
	rows, err := q.db.Query(ctx, listViewStock, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReadViewStock{}
	for rows.Next() {
		var i InventoryReadViewStock
		if err := rows.Scan(
			&i.StockID,
			&i.ProductID,
			&i.ProductName,
			&i.ProductBrands,
			&i.ProductCategories,
			&i.AreaID,
			&i.AreaName,
			&i.QuantityDisplay,
			&i.NetUnit,
			&i.TotalValue,
			&i.Status,
			&i.OwnerPartyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
