// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewShop struct {
	ShopID            pgtype.UUID        `db:"shop_id" json:"shop_id"`
	ShopName          string             `db:"shop_name" json:"shop_name"`
	Status            string             `db:"status" json:"status"`
	Provider          string             `db:"provider" json:"provider"`
	PlaceID           pgtype.Text        `db:"place_id" json:"place_id"`
	PlaceUrl          pgtype.Text        `db:"place_url" json:"place_url"`
	Latitude          pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric     `db:"longitude" json:"longitude"`
	FormattedAddress  string             `db:"formatted_address" json:"formatted_address"`
	AddressComponents []byte             `db:"address_components" json:"address_components"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ViewShoppingList struct {
	ListID       pgtype.UUID        `db:"list_id" json:"list_id"`
	ListName     pgtype.Text        `db:"list_name" json:"list_name"`
	Status       string             `db:"status" json:"status"`
	Items        []byte             `db:"items" json:"items"`
	ShoppingDate pgtype.Date        `db:"shopping_date" json:"shopping_date"`
	ShopID       pgtype.UUID        `db:"shop_id" json:"shop_id"`
	ShopName     pgtype.Text        `db:"shop_name" json:"shop_name"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
