// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetViewShopByID(ctx context.Context, shopID pgtype.UUID) (ViewShop, error)
	GetViewShoppingListByID(ctx context.Context, listID pgtype.UUID) (ViewShoppingList, error)
	ListViewShoppingLists(ctx context.Context, arg ListViewShoppingListsParams) ([]ViewShoppingList, error)
	ListViewShops(ctx context.Context, arg ListViewShopsParams) ([]ViewShop, error)
}

var _ Querier = (*Queries)(nil)
