// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_shops.sql

package dbread

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getViewShopByID = `-- name: GetViewShopByID :one
SELECT shop_id, shop_name, status, provider, place_id, place_url, latitude, longitude, formatted_address, address_components, created_at, updated_at FROM view_shops
WHERE shop_id = $1
`

func (q *Queries) GetViewShopByID(ctx context.Context, shopID pgtype.UUID) (ViewShop, error) {
	row := q.db.QueryRow(ctx, getViewShopByID, shopID)
	var i ViewShop
	err := row.Scan(
		&i.ShopID,
		&i.ShopName,
		&i.Status,
		&i.Provider,
		&i.PlaceID,
		&i.PlaceUrl,
		&i.Latitude,
		&i.Longitude,
		&i.FormattedAddress,
		&i.AddressComponents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewShops = `-- name: ListViewShops :many
SELECT shop_id, shop_name, status, provider, place_id, place_url, latitude, longitude, formatted_address, address_components, created_at, updated_at FROM view_shops
WHERE ($1::timestamptz IS NULL OR (created_at, shop_id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, shop_id DESC
LIMIT $3
`

type ListViewShopsParams struct {
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListViewShops(ctx context.Context, arg ListViewShopsParams) ([]ViewShop, error) {
	rows, err := q.db.Query(ctx, listViewShops, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewShop{}
	for rows.Next() {
		var i ViewShop
		if err := rows.Scan(
			&i.ShopID,
			&i.ShopName,
			&i.Status,
			&i.Provider,
			&i.PlaceID,
			&i.PlaceUrl,
			&i.Latitude,
			&i.Longitude,
			&i.FormattedAddress,
			&i.AddressComponents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
