// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityWriteOutboxArchiveStatus string

const (
	IdentityWriteOutboxArchiveStatusSuccess IdentityWriteOutboxArchiveStatus = "success"
	IdentityWriteOutboxArchiveStatusFailed  IdentityWriteOutboxArchiveStatus = "failed"
)

func (e *IdentityWriteOutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityWriteOutboxArchiveStatus(s)
	case string:
		*e = IdentityWriteOutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityWriteOutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullIdentityWriteOutboxArchiveStatus struct {
	IdentityWriteOutboxArchiveStatus IdentityWriteOutboxArchiveStatus `json:"identity_write_outbox_archive_status"`
	Valid                            bool                             `json:"valid"` // Valid is true if IdentityWriteOutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityWriteOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityWriteOutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityWriteOutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityWriteOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityWriteOutboxArchiveStatus), nil
}

type IdentityWriteOutboxEventStatus string

const (
	IdentityWriteOutboxEventStatusPending    IdentityWriteOutboxEventStatus = "pending"
	IdentityWriteOutboxEventStatusProcessing IdentityWriteOutboxEventStatus = "processing"
	IdentityWriteOutboxEventStatusFailed     IdentityWriteOutboxEventStatus = "failed"
)

func (e *IdentityWriteOutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityWriteOutboxEventStatus(s)
	case string:
		*e = IdentityWriteOutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityWriteOutboxEventStatus: %T", src)
	}
	return nil
}

type NullIdentityWriteOutboxEventStatus struct {
	IdentityWriteOutboxEventStatus IdentityWriteOutboxEventStatus `json:"identity_write_outbox_event_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if IdentityWriteOutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityWriteOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityWriteOutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityWriteOutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityWriteOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityWriteOutboxEventStatus), nil
}

type IdentityWritePartiesStatus string

const (
	IdentityWritePartiesStatusInactive IdentityWritePartiesStatus = "inactive"
	IdentityWritePartiesStatusActive   IdentityWritePartiesStatus = "active"
)

func (e *IdentityWritePartiesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityWritePartiesStatus(s)
	case string:
		*e = IdentityWritePartiesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityWritePartiesStatus: %T", src)
	}
	return nil
}

type NullIdentityWritePartiesStatus struct {
	IdentityWritePartiesStatus IdentityWritePartiesStatus `json:"identity_write_parties_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if IdentityWritePartiesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityWritePartiesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityWritePartiesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityWritePartiesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityWritePartiesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityWritePartiesStatus), nil
}

type IdentityWritePartyMembersRole string

const (
	IdentityWritePartyMembersRoleOwner  IdentityWritePartyMembersRole = "owner"
	IdentityWritePartyMembersRoleAdmin  IdentityWritePartyMembersRole = "admin"
	IdentityWritePartyMembersRoleMember IdentityWritePartyMembersRole = "member"
)

func (e *IdentityWritePartyMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityWritePartyMembersRole(s)
	case string:
		*e = IdentityWritePartyMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityWritePartyMembersRole: %T", src)
	}
	return nil
}

type NullIdentityWritePartyMembersRole struct {
	IdentityWritePartyMembersRole IdentityWritePartyMembersRole `json:"identity_write_party_members_role"`
	Valid                         bool                          `json:"valid"` // Valid is true if IdentityWritePartyMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityWritePartyMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityWritePartyMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityWritePartyMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityWritePartyMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityWritePartyMembersRole), nil
}

type IdentityWriteUsersStatus string

const (
	IdentityWriteUsersStatusInactive IdentityWriteUsersStatus = "inactive"
	IdentityWriteUsersStatusActive   IdentityWriteUsersStatus = "active"
)

func (e *IdentityWriteUsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityWriteUsersStatus(s)
	case string:
		*e = IdentityWriteUsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityWriteUsersStatus: %T", src)
	}
	return nil
}

type NullIdentityWriteUsersStatus struct {
	IdentityWriteUsersStatus IdentityWriteUsersStatus `json:"identity_write_users_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if IdentityWriteUsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityWriteUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityWriteUsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityWriteUsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityWriteUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityWriteUsersStatus), nil
}

type IdentityReadViewParty struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Members   []byte             `db:"members" json:"members"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdentityReadViewUser struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	Email           string             `db:"email" json:"email"`
	Activated       bool               `db:"activated" json:"activated"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	IdpSubjectID    string             `db:"idp_subject_id" json:"idp_subject_id"`
	IdpProviderName string             `db:"idp_provider_name" json:"idp_provider_name"`
	Parties         []byte             `db:"parties" json:"parties"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdentityWriteIdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type IdentityWriteOutboxArchive struct {
	ID             pgtype.UUID                      `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID                      `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID                      `db:"trace_id" json:"trace_id"`
	Event          string                           `db:"event" json:"event"`
	Payload        []byte                           `db:"payload" json:"payload"`
	Status         IdentityWriteOutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32                            `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz               `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz               `db:"archived_at" json:"archived_at"`
}

type IdentityWriteOutboxEvent struct {
	ID         pgtype.UUID                    `db:"id" json:"id"`
	TraceID    pgtype.UUID                    `db:"trace_id" json:"trace_id"`
	Event      string                         `db:"event" json:"event"`
	Payload    []byte                         `db:"payload" json:"payload"`
	Status     IdentityWriteOutboxEventStatus `db:"status" json:"status"`
	RetryCount int32                          `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz             `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz             `db:"updated_at" json:"updated_at"`
}

type IdentityWriteParty struct {
	ID        pgtype.UUID                `db:"id" json:"id"`
	Name      string                     `db:"name" json:"name"`
	Status    IdentityWritePartiesStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz         `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz         `db:"updated_at" json:"updated_at"`
}

type IdentityWritePartyMember struct {
	PartyID   pgtype.UUID                   `db:"party_id" json:"party_id"`
	UserID    pgtype.UUID                   `db:"user_id" json:"user_id"`
	Role      IdentityWritePartyMembersRole `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz            `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz            `db:"updated_at" json:"updated_at"`
}

type IdentityWriteProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type IdentityWriteUser struct {
	ID              pgtype.UUID              `db:"id" json:"id"`
	DisplayName     string                   `db:"display_name" json:"display_name"`
	Email           string                   `db:"email" json:"email"`
	Activated       bool                     `db:"activated" json:"activated"`
	AvatarUrl       pgtype.Text              `db:"avatar_url" json:"avatar_url"`
	IdpSubjectID    string                   `db:"idp_subject_id" json:"idp_subject_id"`
	IdpProviderName string                   `db:"idp_provider_name" json:"idp_provider_name"`
	Status          IdentityWriteUsersStatus `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
}
