// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPartyMember = `-- name: CreatePartyMember :one
INSERT INTO identity_write.party_members (party_id, user_id, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING party_id, user_id, role, created_at, updated_at
`

type CreatePartyMemberParams struct {
	PartyID   pgtype.UUID                   `db:"party_id" json:"party_id"`
	UserID    pgtype.UUID                   `db:"user_id" json:"user_id"`
	Role      IdentityWritePartyMembersRole `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz            `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz            `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePartyMember(ctx context.Context, arg CreatePartyMemberParams) (IdentityWritePartyMember, error) {
	row := q.db.QueryRow(ctx, createPartyMember,
		arg.PartyID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdentityWritePartyMember
	err := row.Scan(
		&i.PartyID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyMember = `-- name: GetPartyMember :one
SELECT party_id, user_id, role, created_at, updated_at FROM identity_write.party_members
WHERE party_id = $1 AND user_id = $2
`

type GetPartyMemberParams struct {
	PartyID pgtype.UUID `db:"party_id" json:"party_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetPartyMember(ctx context.Context, arg GetPartyMemberParams) (IdentityWritePartyMember, error) {
	row := q.db.QueryRow(ctx, getPartyMember, arg.PartyID, arg.UserID)
	var i IdentityWritePartyMember
	err := row.Scan(
		&i.PartyID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removePartyMember = `-- name: RemovePartyMember :exec
DELETE FROM identity_write.party_members
WHERE party_id = $1 AND user_id = $2
`

type RemovePartyMemberParams struct {
	PartyID pgtype.UUID `db:"party_id" json:"party_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemovePartyMember(ctx context.Context, arg RemovePartyMemberParams) error {
	_, err := q.db.Exec(ctx, removePartyMember, arg.PartyID, arg.UserID)
	return err
}

const updatePartyMemberRole = `-- name: UpdatePartyMemberRole :exec
UPDATE identity_write.party_members SET
  role = $3,
  updated_at = $4
WHERE party_id = $1 AND user_id = $2
`

type UpdatePartyMemberRoleParams struct {
	PartyID   pgtype.UUID                   `db:"party_id" json:"party_id"`
	UserID    pgtype.UUID                   `db:"user_id" json:"user_id"`
	Role      IdentityWritePartyMembersRole `db:"role" json:"role"`
	UpdatedAt pgtype.Timestamptz            `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdatePartyMemberRole(ctx context.Context, arg UpdatePartyMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updatePartyMemberRole,
		arg.PartyID,
		arg.UserID,
		arg.Role,
		arg.UpdatedAt,
	)
	return err
}
