// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdentityWriteIdempotencyKey, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (IdentityWriteOutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (IdentityWriteOutboxEvent, error)
	CreateParty(ctx context.Context, arg CreatePartyParams) (IdentityWriteParty, error)
	CreatePartyMember(ctx context.Context, arg CreatePartyMemberParams) (IdentityWritePartyMember, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (IdentityWriteProcessedMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityWriteUser, error)
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (IdentityWriteIdempotencyKey, error)
	GetPartyByID(ctx context.Context, id pgtype.UUID) (IdentityWriteParty, error)
	GetPartyMember(ctx context.Context, arg GetPartyMemberParams) (IdentityWritePartyMember, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]IdentityWriteOutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (IdentityWriteProcessedMessage, error)
	GetUserByEmail(ctx context.Context, email string) (IdentityWriteUser, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (IdentityWriteUser, error)
	GetViewPartyByID(ctx context.Context, id pgtype.UUID) (IdentityReadViewParty, error)
	GetViewUserByID(ctx context.Context, id pgtype.UUID) (IdentityReadViewUser, error)
	ListViewParties(ctx context.Context, arg ListViewPartiesParams) ([]IdentityReadViewParty, error)
	ListViewUsers(ctx context.Context, arg ListViewUsersParams) ([]IdentityReadViewUser, error)
	RemovePartyMember(ctx context.Context, arg RemovePartyMemberParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (IdentityWriteOutboxEvent, error)
	UpdateParty(ctx context.Context, arg UpdatePartyParams) (IdentityWriteParty, error)
	UpdatePartyMemberRole(ctx context.Context, arg UpdatePartyMemberRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (IdentityWriteUser, error)
}

var _ Querier = (*Queries)(nil)
