// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO cookbook_write.idempotency_keys (key_id, request_hash, response, status_code, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING key_id, request_hash, response, status_code, created_at
`

type CreateIdempotencyKeyParams struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (CookbookWriteIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.KeyID,
		arg.RequestHash,
		arg.Response,
		arg.StatusCode,
		arg.CreatedAt,
	)
	var i CookbookWriteIdempotencyKey
	err := row.Scan(
		&i.KeyID,
		&i.RequestHash,
		&i.Response,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKeyByID = `-- name: GetIdempotencyKeyByID :one
SELECT key_id, request_hash, response, status_code, created_at FROM cookbook_write.idempotency_keys
WHERE key_id = $1
`

func (q *Queries) GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (CookbookWriteIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyByID, keyID)
	var i CookbookWriteIdempotencyKey
	err := row.Scan(
		&i.KeyID,
		&i.RequestHash,
		&i.Response,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}
