// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CookbookWriteOutboxArchiveStatus string

const (
	CookbookWriteOutboxArchiveStatusSuccess CookbookWriteOutboxArchiveStatus = "success"
	CookbookWriteOutboxArchiveStatusFailed  CookbookWriteOutboxArchiveStatus = "failed"
)

func (e *CookbookWriteOutboxArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CookbookWriteOutboxArchiveStatus(s)
	case string:
		*e = CookbookWriteOutboxArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CookbookWriteOutboxArchiveStatus: %T", src)
	}
	return nil
}

type NullCookbookWriteOutboxArchiveStatus struct {
	CookbookWriteOutboxArchiveStatus CookbookWriteOutboxArchiveStatus `json:"cookbook_write_outbox_archive_status"`
	Valid                            bool                             `json:"valid"` // Valid is true if CookbookWriteOutboxArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCookbookWriteOutboxArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CookbookWriteOutboxArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CookbookWriteOutboxArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCookbookWriteOutboxArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CookbookWriteOutboxArchiveStatus), nil
}

type CookbookWriteOutboxEventStatus string

const (
	CookbookWriteOutboxEventStatusPending    CookbookWriteOutboxEventStatus = "pending"
	CookbookWriteOutboxEventStatusProcessing CookbookWriteOutboxEventStatus = "processing"
	CookbookWriteOutboxEventStatusFailed     CookbookWriteOutboxEventStatus = "failed"
)

func (e *CookbookWriteOutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CookbookWriteOutboxEventStatus(s)
	case string:
		*e = CookbookWriteOutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CookbookWriteOutboxEventStatus: %T", src)
	}
	return nil
}

type NullCookbookWriteOutboxEventStatus struct {
	CookbookWriteOutboxEventStatus CookbookWriteOutboxEventStatus `json:"cookbook_write_outbox_event_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if CookbookWriteOutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCookbookWriteOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CookbookWriteOutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CookbookWriteOutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCookbookWriteOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CookbookWriteOutboxEventStatus), nil
}

type CookbookWriteRecipesStatus string

const (
	CookbookWriteRecipesStatusDraft    CookbookWriteRecipesStatus = "draft"
	CookbookWriteRecipesStatusInactive CookbookWriteRecipesStatus = "inactive"
	CookbookWriteRecipesStatusActive   CookbookWriteRecipesStatus = "active"
)

func (e *CookbookWriteRecipesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CookbookWriteRecipesStatus(s)
	case string:
		*e = CookbookWriteRecipesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CookbookWriteRecipesStatus: %T", src)
	}
	return nil
}

type NullCookbookWriteRecipesStatus struct {
	CookbookWriteRecipesStatus CookbookWriteRecipesStatus `json:"cookbook_write_recipes_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if CookbookWriteRecipesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCookbookWriteRecipesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CookbookWriteRecipesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CookbookWriteRecipesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCookbookWriteRecipesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CookbookWriteRecipesStatus), nil
}

type CookbookWriteRecipesVisibility string

const (
	CookbookWriteRecipesVisibilityOfficial  CookbookWriteRecipesVisibility = "official"
	CookbookWriteRecipesVisibilityCommunity CookbookWriteRecipesVisibility = "community"
	CookbookWriteRecipesVisibilityPrivate   CookbookWriteRecipesVisibility = "private"
)

func (e *CookbookWriteRecipesVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CookbookWriteRecipesVisibility(s)
	case string:
		*e = CookbookWriteRecipesVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for CookbookWriteRecipesVisibility: %T", src)
	}
	return nil
}

type NullCookbookWriteRecipesVisibility struct {
	CookbookWriteRecipesVisibility CookbookWriteRecipesVisibility `json:"cookbook_write_recipes_visibility"`
	Valid                          bool                           `json:"valid"` // Valid is true if CookbookWriteRecipesVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCookbookWriteRecipesVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.CookbookWriteRecipesVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CookbookWriteRecipesVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCookbookWriteRecipesVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CookbookWriteRecipesVisibility), nil
}

type CookbookReadViewRecipe struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Status       string             `db:"status" json:"status"`
	Instructions []byte             `db:"instructions" json:"instructions"`
	Ingredients  []byte             `db:"ingredients" json:"ingredients"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	OwnerPartyID pgtype.UUID        `db:"owner_party_id" json:"owner_party_id"`
	Visibility   string             `db:"visibility" json:"visibility"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    string             `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text        `db:"updated_by" json:"updated_by"`
}

type CookbookWriteIdempotencyKey struct {
	KeyID       pgtype.UUID        `db:"key_id" json:"key_id"`
	RequestHash string             `db:"request_hash" json:"request_hash"`
	Response    []byte             `db:"response" json:"response"`
	StatusCode  int32              `db:"status_code" json:"status_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CookbookWriteIngredient struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	RecipeID   pgtype.UUID        `db:"recipe_id" json:"recipe_id"`
	ProductIds []pgtype.UUID      `db:"product_ids" json:"product_ids"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy  pgtype.Text        `db:"updated_by" json:"updated_by"`
}

type CookbookWriteOutboxArchive struct {
	ID             pgtype.UUID                      `db:"id" json:"id"`
	OutboxEventID  pgtype.UUID                      `db:"outbox_event_id" json:"outbox_event_id"`
	TraceID        pgtype.UUID                      `db:"trace_id" json:"trace_id"`
	Event          string                           `db:"event" json:"event"`
	Payload        []byte                           `db:"payload" json:"payload"`
	Status         CookbookWriteOutboxArchiveStatus `db:"status" json:"status"`
	RetryCount     int32                            `db:"retry_count" json:"retry_count"`
	EventCreatedAt pgtype.Timestamptz               `db:"event_created_at" json:"event_created_at"`
	ArchivedAt     pgtype.Timestamptz               `db:"archived_at" json:"archived_at"`
}

type CookbookWriteOutboxEvent struct {
	ID         pgtype.UUID                    `db:"id" json:"id"`
	TraceID    pgtype.UUID                    `db:"trace_id" json:"trace_id"`
	Event      string                         `db:"event" json:"event"`
	Payload    []byte                         `db:"payload" json:"payload"`
	Status     CookbookWriteOutboxEventStatus `db:"status" json:"status"`
	RetryCount int32                          `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz             `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz             `db:"updated_at" json:"updated_at"`
}

type CookbookWriteProcessedMessage struct {
	MessageID   string             `db:"message_id" json:"message_id"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type CookbookWriteRecipe struct {
	ID           pgtype.UUID                    `db:"id" json:"id"`
	Name         string                         `db:"name" json:"name"`
	Status       CookbookWriteRecipesStatus     `db:"status" json:"status"`
	Visibility   CookbookWriteRecipesVisibility `db:"visibility" json:"visibility"`
	Instructions []byte                         `db:"instructions" json:"instructions"`
	OwnerID      pgtype.UUID                    `db:"owner_id" json:"owner_id"`
	OwnerPartyID pgtype.UUID                    `db:"owner_party_id" json:"owner_party_id"`
	CreatedAt    pgtype.Timestamptz             `db:"created_at" json:"created_at"`
	CreatedBy    string                         `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz             `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Text                    `db:"updated_by" json:"updated_by"`
	DeletedAt    pgtype.Timestamptz             `db:"deleted_at" json:"deleted_at"`
	DeletedBy    pgtype.Text                    `db:"deleted_by" json:"deleted_by"`
}
