// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (CookbookWriteIdempotencyKey, error)
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (CookbookWriteIngredient, error)
	CreateOutboxArchive(ctx context.Context, arg CreateOutboxArchiveParams) (CookbookWriteOutboxArchive, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CookbookWriteOutboxEvent, error)
	CreateProcessedMessage(ctx context.Context, arg CreateProcessedMessageParams) (CookbookWriteProcessedMessage, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (CookbookWriteRecipe, error)
	DeleteIngredient(ctx context.Context, id pgtype.UUID) error
	GetIdempotencyKeyByID(ctx context.Context, keyID pgtype.UUID) (CookbookWriteIdempotencyKey, error)
	GetIngredientByID(ctx context.Context, id pgtype.UUID) (CookbookWriteIngredient, error)
	GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]CookbookWriteOutboxEvent, error)
	GetProcessedMessageByID(ctx context.Context, messageID string) (CookbookWriteProcessedMessage, error)
	GetRecipeByID(ctx context.Context, id pgtype.UUID) (CookbookWriteRecipe, error)
	GetViewRecipeByID(ctx context.Context, id pgtype.UUID) (CookbookReadViewRecipe, error)
	ListViewRecipes(ctx context.Context, arg ListViewRecipesParams) ([]CookbookReadViewRecipe, error)
	SoftDeleteRecipe(ctx context.Context, arg SoftDeleteRecipeParams) error
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (CookbookWriteIngredient, error)
	UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) (CookbookWriteOutboxEvent, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (CookbookWriteRecipe, error)
}

var _ Querier = (*Queries)(nil)
